### ISSUE TITLE
Social media posting tool (what do we have / should we have)

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#1007]
**The need**: Want a tool that ... 

- helps us author and design (or at least easily add those)
- helps us post (schedule etc). In order or priority ...
  - LinkedIn
  - Facebook
  - Twitter
  - Instagram
- tracking and analytics (nice to have in one place)

## Acceptance

- [x] We have a chosen tool(s) for social media posting etc **✅2024-07-03 use Canva or just post directly with the tool**
- [x] Have longlist and shortlist with short info and price
- [x] We have documented this in the tao/communications etc **✅2024-07-03 ❌ wontfix for now as not that important and we are still experimenting**

### Shortlist for posting

(First stab by @rufuspollock - changes welcome)

- Canva: need pro at ~$100/y 
- Typeshare - kind of a different model and more about writing stuff. $200/y

Also-rans

- https://later.com - rather instagram and influencer oriented. It is free though (for some stuff)
- https://Buffer.com: kinda of pricey especially once you add channels. $6/month / channel => $18/month for us w/ eg 3 channels
- https://mixpost.app - nice and open source but you have to self-host ...

Lauren Notes (personally previously used)
- Planoly 
- Hootsuite
- Later (mentioned above)
- Loomly (not previously used competitor or Hootsuite)

Questions

- [x] Do we already have a canva pro subscription 📝 _Canva Premium is free for nonprofits - this is what we have currently_
- [ ] Do we want to list "AI" tools that help with authoring?

### Shortlist for analytics

...

### Background

We have the following social media (all with no subscriptions):

- Instagram
- Facebook
- Twitter
- LinkedIn
- YouTube
- (Whatsapp) 

We have the following tools

Subscriptions/Services used to support posting

- Canva
- Spotify Podcaster (previously Anchor) 💲 
- Midjourney 💲 
- Bitly
- Linktree
- Brevo 💲 
- Tito
- Eventbrite#

### Notes from Akram 

Canva: You mentioned we already have a pro subscription which is perfect. Even the free version has enough features and templates, but with the pro subscription, you don't need any other tool for graphics and social media posts. It is very efficient and simple to use. 
Typeshare: Never used it personally, but it is very similar to a Notion template I use to organize my freelance writing work. Could be beneficial for the team to organize ideas and future posts. 
Later: The free features are quite limited and if you decide to use this tool, you will definitely need to pay for a subscription shortly down the line, and it's a bit pricey. 
Buffer: The one attractive feature about this tool is that it tells you the ideal time to post content, which I don't feel is necessary at this stage for Life Itself's accounts. This is more relevant for accounts with dozens of thousands of followers who actively compete against similarily big accounts to get pushed by the algorithm. Could be useful later, but like Later, it will require a paid subscription. 
Buffer: All of its features could be obtained for free through Notion. 

Tools to consider:
The Built-In Analytics: Every social media platform has its own built-in analytics tool. Using a paid external tool does save a lot of time, but if you want to cut down on costs, using the free features in these platforms provides the same amount of data, and you can keep track of it through Google Sheets or a Notion template.
Cyfe: A social media tool designed towards tracking metrics and can include all platforms at once. Prices start at 19 dollars per month with a 14 days free trial.
Sendible: "a social media management tool with considerable monitoring, listening, and reporting features. It gives you ready-to-use insights into social media post engagement, mentions, and audience profiles across digital channels. Sendible also lets you track what's being said about your brand on various web and social platforms and identifies mentions that might need your attention or response." This last feature can be very helpful to monitor online discussions about the organization and identify potential topics for future content. Prices start at 29 dollars per month. 
Zoho Social: another tool for tracking social media metrics, but the unique feature it offers is displaying the forms of content your audience interacts with the most. Prices start at 10 dollars per month.

**Comment by rufuspollock** [comment]
@laurenwigmore could you update quickly on what we currently have plus any thoughts on this ... (i started this issue because i was looking around for this and wondered what we already had ...)

**Comment by rufuspollock** [comment]
@laurenwigmore do we have any tool we use scheduling or posting social media stuff across platforms - or do we post to each individual platform?

**Comment by laurenwigmore** [comment]
> @laurenwigmore do we have any tool we use scheduling or posting social media stuff across platforms - or do we post to each individual platform?

No at the moment we post on each platform individually. There was the option to use Meta Planner (for IG & FB) but we don't post on FB so this hasn't been used (or at least not since I've been with LI)

**Comment by laurenwigmore** [comment]
Low priority. Useful for when we have a consistency of regularly posting. No further research or actions taken since Akram's notes. My suggestion if we wanted to trial would be to use canva (although it omits twitter). Loomly and Hootsuite are other schedulers to consider when we look at this more (added above).

**Comment by rufuspollock** [comment]
FIXED. Use Canva Pro for now. It's free.

Also moved discussion on this to https://github.com/orgs/comparethe/discussions/4
