### ISSUE TITLE
Documenting Sympoiesis 3

### ISSUE THREAD

**Issue by theo-cox** [life-itself/community#111]
We want great content out of the Sympoiesis 3 residency for our comms effort. See here for the full list: https://docs.google.com/document/d/1kquLdluAWUZ-DfJAdSTWQJZF15InKbR5PKtue_6JeSM/edit?usp=sharing

## Acceptance
- [x] List reviewed by @rufuspollock 
- [ ]  @rufuspollock has discussed clarifications or blockers with @theo-cox and/or @nathenf 
- [ ] Content captured, uploaded to shared drive and flagged to @nathenf

**Comment by theo-cox** [comment]
@rufuspollock given the start date of your residency please review the above list this week, in case we need to discuss anything pre-Xmas

**Comment by Liyubov** [comment]
Hey, 
I was wondering if there is anyone, who is documenting (qualitatively), how people are using the space during different Sympoiesis #1,2,3? 

Materials collected on space-community for Sympoeiesis#2 are on the page of research of life itself folder here https://github.com/life-itself/community/tree/main/research
and I collect some comments and documents in google doc here (welcome any comments) https://docs.google.com/document/d/1wy4fFZ-ympMCR_FeMrWTs_Dz8buWgABRBrVrSj203tE/edit 
I could not read the google doc you shared, but probably it is not on usability of space itself right? @theo-cox @rufuspollock

**Comment by rufuspollock** [comment]
@theo-cox I am happy to leave this to you Nathen and Julie. If you do want my input could it be a succinct summary of questions for me?

**Comment by theo-cox** [comment]
@Liyubov no, although that looks like amazing work! Would it be ok if you picked up with @nathenf around the possibility of us sharing it more broadly through out channels?

@juliedayot could you look into briefly documenting how space is used during Sympoiesis 3 as per the above

**Comment by nathenf** [comment]
FIXED - We made some posts on Instagram and Twitter and a reflection blog post was made by @juliedayot
