### ISSUE TITLE
Live event and interview with Stephen Markley author of the Deluge

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#1125]
## Acceptance

- [x] Development: Publicized event **✅2024-09-17 https://news.lifeitself.org/p/imagining-climate-change-with-stephen**
- [x] Production: Done interview and recorded talk **✅2024-09-20**
- [ ] Post-production: prep post and recording etc
- [ ] Marketing: Published and shared material

### Development

- [x] Decide whether we buy an iphone (or borrow one) for the interview **✅2024-09-21 we purchased an iphone as old one at hub has gone missing it seems**
  - [x] Evaluate options and price
  - [x] Does waiting make any difference?
- [x] Coordinate with Liam around schedule ...
  - [x] Sent message to Liam and Jadzia **✅2024-09-14**
  - [x] Interview may be possible on Friday
- [x] Create a post **✅2024-09-17 by Lauren**

### Production

- [x] Do an interview
  - [x] Prep the interview - see below
  - [x] Conduct the interview **✅2024-09-20. We did**
- [x] Talk and Q&A
  - [x] Record the talk and Q&A
- [x] Upload talk to drive **✅2024-09-24 see https://drive.google.com/drive/u/0/folders/15KcICrRMi7FeRI4s8j0_jWMuj0inNmnP**

```[tasklist]
### Post-production
- [x] Decide on new post vs updating existing post ... **✅2024-09-24 new post and old post can link to this**
- [x] Decide whether worth an email out to whole list **✅2024-09-24 NOT worth emailing whole list IMO but can add to newsletter**
- [x] Put on youtube and/or just post on substack (we can only have one video on substack) **✅2024-09-24 put on youtube is easiest especially as we could have a playlist which saves us having to combine 3 parts of talk together (for some reason camerwoman decided to stop and restart 😉**
- [x] Write blurb ... (could use interview notes below) **🚧2024-09-24 suggest using interview notes below plus a brief lead-in comment giving context on interview and talk - can reuse what we had. Make sure to credit CMP prominently and mention that Rupert Read as facilitator of talk (perhaps could just have another picture with a caption "Stephen Markley giving a talk at the Life Itself Praxis Hub in Bergerac with host Rupert Read of the Climate Majority Project {LINK}"**
- [ ] Extract on image from interview for use in post etc (?)
```

```[tasklist]
### Marketing
- [ ] Make post live
- [ ] Promote on social media and channels ...
- [ ] Add to next newsletter
```

### Introduction

Stephen, thank you for joining us. A clear starting point would be discussing what motivated you to write *The Deluge*. For those unfamiliar, *The Deluge* is an epic, dystopian yet occasionally hopeful novel that traces how the climate crisis might unfold between 2013 and 2040. Set primarily in the US, the book explores a broad cast of characters—from eco-terrorists and activists to politicians and policymakers—as they navigate this period of ecological and social upheaval. The narrative moves from our present realities into speculative futures, making it both a work of fiction and a possible foresight exercise.  

At Life Itself, we’re particularly interested in the broader context of societal transition, which we refer to as the "second renaissance" — a shift driven by what many see as a *meta-crisis* rooted in the foundations of our current social and cultural systems.

Your novel seems to be grappling with this theme, portraying what we might call the "dark renaissance": an initial crisis that can then catalyse a transition to a better future. That leads us to wonder about your thoughts on the possibilities for renewal or transformation.

**Questions**

1. What motivated you to write *The Deluge*?  
2. What do you most hope to communicate through this book?  
3. Your book the *Deluge* gives a somewhat dystopian vision of our future, though there are glimmers of hope. What do you see as the most hopeful possibilities that could emerge from the crises we face?  
4. We’re interested in this concept of a "second renaissance," where art and fiction help envision the future. How do you see fiction playing a role in societal transformation?

**Comment by rufuspollock** [comment]
@laurenwigmore i've booted this issue for us and recorded current status. This is another thing we can push out next week.

**Comment by rufuspollock** [comment]
@laurenwigmore ok, videos are uploaded and linked above and i've made some suggestions. Suggest we get this up asap e.g. today or tomorrow. Another thing for Radha to practice sharing on socials 😉

**Comment by laurenwigmore** [comment]
Update: Bijesh to edit Part I (due to framing issue) and combine 3 videos. Post and YT copy, and canva graphic drafted ready to go live. 
Radha updated to include this video in her social media promotion towards the end of this week.
I will contact Liam/Jazdia/Rupert once I have the edited video back and check with them they are OK before publishing.
Aim: to publish 3pm CET Thursday 26.09.24.

**Comment by laurenwigmore** [comment]
FIXED. Interview live on YouTube, and Substack post up. Radha assigned social media promotion.
