### ISSUE TITLE
Add materials for studying communities life and communities spaces

### ISSUE THREAD

**Issue by Liyubov** [life-itself/community#114]
The key questions explored in this piece are: 

* What does community life look like in Life itself?
* Can we replicate or encapsulate the experience lived by community members to be able to transmit best practices to other community hubs?

To answer these questions, we define and explore the entire phase space* of activities as well as spaces of living areas. It’s only by understanding the whole space in combination with activities that we can identify the key community characteristics.

## Tasks

- [ ] Write method for studying community spaces and documenting community life  
The main document in progress is here https://docs.google.com/document/d/1iEnEU04ZiTpLjhlxp2QlZ9Va9SOymxn3YB-2lADdKcM/edit?usp=sharing 

About the method we develop with M.S. during our stay in Sympoesis #2  . This method for studying communities can be further developed and used in more general contexts such as studies of intentional communities. We define and explore the entire phase space* of activities as well as spaces of living areas. It’s only by understanding the whole space in combination with activities that we can identify the key community characteristics. 
Let me know if any comments are needed. 

- [ ] Integrate this method into other contexts, e.g. for other repos of Life itself ic.org (intentional communities) https://github.com/life-itself/intentional-communities

**Comment by rufuspollock** [comment]
@Liyubov this is great and i think the draft already looks like it could become an initial blog piece.

**Comment by Liyubov** [comment]
The update on communities studies: 
Penny and colleague of hers from Coliving Summit proposed to coorganise the small research group, information about which can be disseminated and hosted by coliv, life itself. The main topic of the group is investigation of coliving spaces at different scales: from 1 flat scale to the scale of 1 eco village. More details will come soon.
