### ISSUE TITLE
First Issues for Catherine to try out

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#120]
When starting out I want some nice first issues to get started with that give me context, are interested and make a contribution

## Tasks

* [ ] Rufus generate a backlog
* [x] Proof edit (and review) Conscious Food Organization draft https://docs.google.com/document/d/1wbiMvrqTkqJuQ-X3kK3dEURNRE_337kNaqM77gFemlg/edit# **Done - asked Valerie to review comments and suggestions, and to add to/edit mandala tool section**
* [ ] ...

**Comment by catherinet1** [comment]
I reviewed conscious food org doc and asked Valerie to review comments/suggestions

**Comment by Liyubov** [comment]
Hey, I also reviewed it, as we discussed it with Valerie and added some references. Hope it was not too late to add some material there.

**Comment by rufuspollock** [comment]
@Liyubov that's great.

**Comment by rufuspollock** [comment]
FIXED. This is now done / obsolete.
