### ISSUE TITLE
Add Insight, Interbeing and Science Residency to the Residencies tab

### ISSUE THREAD

**Issue by EilidhRoss1** [life-itself/community#131]
The Insight, Interbeing and Science Residency has been announced as a [blog](https://lifeitself.us/2022/02/07/insight-interbeing-and-science-may-2022/) but isn't under the Residencies tab on the website. 

### Acceptance

- [ ] Create page on the website for the Insight, Interbeing and Science Residency. 
- [ ] Add page to the [Residency tab](https://lifeitself.us/sympoiesis/)

**Comment by EilidhRoss1** [comment]
@lkavanagh30 @rufuspollock could one of you please look at this.

**Comment by rufuspollock** [comment]
@EilidhRoss1 I didn't think i was involved in this residency so I imagine this falls to @lkavanagh30

Liam are you happy to take this on?

**Comment by EilidhRoss1** [comment]
Page on the website has been created for the Insight, Interbeing and Science Residency. The page has been added to the Residency tab
