### ISSUE TITLE
[draft] Evaluation of current website platform and alternatives

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#136]
### Evaluation of current Wordpress Site

Lighthouse score is 

![image](https://user-images.githubusercontent.com/180658/160101930-169505a2-b75f-4ba6-a08b-9c9eaacfa63b.png)

[lifeitself.us - lighthouse report - 2022-03-25.pdf](https://github.com/life-itself/community/files/8349467/lifeitself.us.-.lighthouse.report.-.2022-03-25.pdf)

**Comment by nathenf** [comment]
MERGED - #170 and [platform migration A10](https://docs.google.com/document/d/1fhl4quGen3KmglOYzfG6MXAbk7yR2H87weeN8ACqxBg/edit#)
