### ISSUE TITLE
Create assets repo and assets.lifeitself.org for hosting common image and static assets

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#138]
Create an assets repo with core brand assets like logo and deploy it in a reusable location e.g. assets.lifeitself.org

Project page: https://github.com/life-itself/community/blob/main/projects/assets-repo-v1-2022.md

## Acceptance

* [x] assets repo exists in life-itself **✅2022-04-29 https://github.com/life-itself/assets**
* [x] assets.lifeitself.org builds from that on e.g. cloudflare **✅2022-04-29 https://assets.lifeitself.org/**
* [x] life itself logo and logo-type is in there (in various versions) **🚧2022-04-29 https://assets.lifeitself.org/lifeitself/img/life-itself-logo.svg is there**

**Comment by nathenf** [comment]
@rufuspollock assume we can close this now

**Comment by rufuspollock** [comment]
FIXED. But does not seem to be working as of now e.g. https://assets.lifeitself.org/lifeitself/img/life-itself-logo.svg 404s.
