### ISSUE TITLE
Life Itself slow loading

### ISSUE THREAD

**Issue by EilidhRoss1** [life-itself/community#145]
**Situation:** Life Itself site is taking very long to load. It is off-putting for users and inconvenient for LI members wanting to use the site. 

**Question:** What is the problem and how do we fix it?

**Hypothesis:** @khalilcodes: "This happens due to a few factors such as hosting service and WordPress overall."

## Acceptance

- [ ] Improve website loading times / page speed (*for end users and members*)

## Tasks

- [ ] Research cause for low page speeds

## Questions

- Does this happen only for members *or* also for the end users eg. after editing the page, it may not load properly for editors/members when previewing but loads correctly and a bit faster when opening in incognito mode ? This is a common wordpress issue in my experience.

## Suggestions

- Redo the website on the frontend using Nextjs and keep the current wordpress as a headless cms for editors. ? @rufuspollock

**Comment by nathenf** [comment]
WONTFIX - Migrating from Wordpress to Next.Js
