### ISSUE TITLE
Can orgs be sound *and* successful?

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#160]
**Can orgs be sound *and* successful?**: Is it really possible to have organizations that are for-profit, with shared ownership, a true purpose (other than making money) ... and still be successful and scalable and what does that exactly look like in terms of the details of ownership, governance and culture?

Alternative titles:

- How to cooperate
- Can orgs be sound *and* successful?
- Why reinventing orgs is harder than you think and how to make it easier

## Acceptance

* [x] SCQH and outline done
  * [ ] BONUS: validate this with a few people (does the topic sound useful and interesting) 
* [x] Draft white paper ready for circulation and comments. Note we may break this paper into parts e.g.
  * [ ] Horizon scan: what is "sound", what org types are out there and how do they measure up against "sound" and "successful"
  * [ ] Challenges including toy model of an org
  * [ ] Design principles
* [x] White paper published e.g. on labs site or elsewhere **https://labs.lifeitself.org/writing/co-ops**
* [x] White paper circulated to interested parties and shared on relevant fora
  * [x] Newsletter
  * [ ] Labs list
  * [x] Fora **DBWT conference**

### Planning

* [x] SCQ(H)
* [x] Issue tree sketch
* [ ] Issue tree detailed (spreadsheet) **In progress: https://docs.google.com/spreadsheets/d/12qeV5Nj_pX_BGAgne5X6po_kuWjjPvuJSE4P-rjb6xI/edit?usp=sharing**
* [ ] Initial plan of work **Brainstorming here: https://docs.google.com/document/d/1faAgWSQ2T8TRArwhMQmbdtWt5jwYWg5aBhrXlh0FORo/edit#heading=h.ej3dbpc0eluz**

### Implementation

```mermaid
graph TD

goals --> toy
toy --> toydetails[theory of orgs]
toydetails --> tensions
tensions --> options
options --> eval[Evaluate options]
eval --> next[?]
```

**Comment by theo-cox** [comment]
Brainstorm of preliminary theoretical problems completed, along with draft opening of our toy example. See: https://docs.google.com/document/d/1faAgWSQ2T8TRArwhMQmbdtWt5jwYWg5aBhrXlh0FORo/edit?usp=sharing

**Comment by rufuspollock** [comment]
@theo-cox do you want to update this issue with latest developments. Also shall we post the SCQH?

**Comment by theo-cox** [comment]
FIXED. The direction of the project ended up shifting somewhat after preliminary research, but we published a whitepaper containing a very rigorous and extensive review of the econ literature https://labs.lifeitself.org/writing/co-ops. Theo also presented his work at the Doing Better Work Together Conference, an got a very positive reception

**Comment by rufuspollock** [comment]
some notes for future readers of this issue (think we can leave closed for now):

- i guess we could have published the SCQH? but maybe it is just the white paper itself.
- I also wonder if we could get the full paper up as markdown and not just as pdf? (not a priority though - just a note for future readers of this issue).
