### ISSUE TITLE
Monthly Newsletter Update

### ISSUE THREAD

**Issue by nathenf** [life-itself/community#176]
##Acceptance

- [ ] Email sent

##To Include

- Upcoming Residencies
- Mapping Metamodern Update
- Latest Media
- Features 
- Updates from Residencies
- Berlin Update

Email eilidh@lifeitself.org if you wish to have anything included in the next newsletter.

**Comment by rufuspollock** [comment]
@nathenf is this an issue or more documentation for how we do the newsletter? If the latter maybe we move to tao or discussions?

**Comment by nathenf** [comment]
@rufuspollock perhaps this could be turned into a documentation and added to tao. Maybe a good first exercise for me to use Obsidian etc

**Comment by EilidhRoss1** [comment]
@nathenf suggestion we close this and set up a new issue for you to move to tao

**Comment by nathenf** [comment]
DEPRECATED - No longer required to have this. Once we know our email strategy we can add information to the Tao or Notes.
