### ISSUE TITLE
Migration of ecosystem.lifeitself.org to lifeitself.org II

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#183]
Following on from #167 which did basic content migration.

- [ ] How do we want ecosystem to integrate into the main site - is it a separate mini-section or more central. e.g. do we connect with notebook entries on particular orgs. e.g. when writing notes about an org do we put it in ecosystem or in notebook? TODO: write some job stories here
- [ ] what do we do with current content at lifeitself.org/ecosystem? (migrate to markdown and relcoate somehow?) Or move to an old blog post?
- [ ] how do we make editing and contributing super easy?
	- [ ] could we add commenting perhaps to these pages?
- [ ] how do we locate images in ecosystem mini-project folder so work nicely on site
- [ ] should ecosystem folder move into the vault? Why? Why not?

**Comment by nathenf** [comment]
@rufuspollock is this done?

**Comment by rufuspollock** [comment]
No, #167 is done. this is follow-up.

**Comment by rufuspollock** [comment]
INVALID / DUPLICATE. Consolidated this back into #170
