### ISSUE TITLE
Website 2022 design including job stories, info architecture etc

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#195]
## Acceptance

- [ ] What is the layout (information architecture) of the digital garden (and life itself site in general)?
- [ ] How do we have subsections of site (given its size) e.g. notebook section vs tao section vs ...
- [ ] What are our categories

## Analysis

```
# landing pages
/            # home
/newsletter  
/programs    # e.g. residencies etc

# optional
/podcast

# hubs?? or is this in tao now?
/hubs ??

# resources
/about
/initiatives/ - a full list of all our activities
```

## Categories

- News => used for all real news e.g. launch or major updates to initiatives, partnerships, etc ...
- Events => for events (may also be in news) => so that we can have an /events/ page run off this ...
- Topics

**Comment by nathenf** [comment]
MERGED - Description here is merged into #223 as this is primarily about refactoring (for which we will make job stories). Actually design will come at a later stage once structure is finalized
