### ISSUE TITLE
logo for Praxis Bergerac hub

### ISSUE THREAD

**Issue by Liyubov** [life-itself/community#258]
Hi, @rufuspollock and all, 
As Valerie was asking a question about the logo, so copying it here:

"Regarding the logo of Bergerac Praxis hub, shall we use the yellow logo and just put the name below or like Labs, to use only the bird ( still looking north west) and the name on the left, what do you think, is there a policy on that?"

This is just to understand for future comms and materials to send around regarding future residencies.

Thank you.

**Comment by Liyubov** [comment]
Here are options for the logos, which ones would work then for praxis hub? Valerie was asking them before residencies start 
https://docs.google.com/document/d/1W3bdw1kgpl7HocApv6C7pp0tGVKOhXKc/edit?usp=sharing&ouid=101801363676323259669&rtpof=true&sd=true

Thanks in advance.

**Comment by rufuspollock** [comment]
@Liyubov thanks for raising. We are in process of updating things on this front a bit. For now i think simplest is you can get the source SVG and we play with it. We should create a proper page about this in the tao (see #266).

Here's suggestion of layout in excalidraw: https://app.excalidraw.com/l/9u8crB2ZmUo/PicAUjW9TK (editable)

![image](https://user-images.githubusercontent.com/180658/212940880-5f6af08b-3cf1-4c14-93be-d448f3753e45.png)

**Comment by Liyubov** [comment]
ok thanks @rufuspollock we will then look at the excalidraw and edit them. 
our main question was more regarding fonts which ones to use? 
or is it up to us to discuss?

**Comment by rufuspollock** [comment]
I would use the standard font we use which is mentioned in #181 i think. BTW the excalidraw is just examples of layouts - it's not the place to edit really. What we need to do is get the page into the tao in #266 - if someone were up for helping with that!

**Comment by nathenf** [comment]
@rufuspollock @Liyubov where are we at with this? I can easily fix up a logo with the correct font and send it over if needed.

**Comment by Liyubov** [comment]
@nathenf for now i was waiting for the reply on which fonts are better to use, here is the editable file with logos, would it please be possible to check for you which are the best option for font for logo? thank you!
https://docs.google.com/document/d/1W3bdw1kgpl7HocApv6C7pp0tGVKOhXKc/edit?usp=sharing&ouid=101801363676323259669&rtpof=true&sd=true

**Comment by rufuspollock** [comment]
> @rufuspollock @Liyubov where are we at with this? I can easily fix up a logo with the correct font and send it over if needed.

For future practice better if we create a process others can follow so we are self sufficient. (Though if a lot more effort just doing directly is fine.)

**Comment by nathenf** [comment]
FIXED - Logo is created and sent to @Liyubov and Tao logo page updated with logo creation process see: https://lifeitself.org/tao/communications/logos

**Comment by Liyubov** [comment]
@nathenf thanks, when I try to access this page I get 404 error

**Comment by nathenf** [comment]
@Liyubov apologies, updated url is lifeitself.org/tao/logos
