### ISSUE TITLE
Make comms protocols and guides

### ISSUE THREAD

**Issue by EilidhRoss1** [life-itself/community#277]
When Eilidh leaves we want it to be easy for someone else to pick up her comms tasks. We can do this by having clearly written protocols.

## Acceptance

- [x] Protocol and guidance on how to produce a podcast episode is published to tao ✅ **https://github.com/life-itself/community/blob/main/vault/tao/communications/producing-a-podcast-episode-guide.md**
- [x] Protocol and guidance on how to use Instagram is published to tao ✅ **https://github.com/life-itself/community/blob/main/vault/tao/communications/publishing-an-instagram-post.md** 
- [x] Protocol and guidance on how to use Twitter is published to tao ✅ **link to google doc and how to write a thread in [communications page](https://lifeitself.org/tao/communications)**
- [x] Protocol and guidance on how to publish a blog is published to tao ✅ **https://lifeitself.org/tao/tao/communications/guide-to-uploading-blogs**
- [x] Protocol and guidance on how to produce the monthly newsletter is published to tao ✅ **https://lifeitself.org/tao/tao/communications/creating-the-monthly-newsletter**

**Comment by rufuspollock** [comment]
@EilidhRoss1 i would keep these as minimal as possible as things rapidly change. I imagine there are roughly two parts here:

- Access to infrastructure (i imagine this can be largely links to existing good docs for products themselves plus instructions to look in bitwarden for logins etc)
- Howtos on how to prep content:
  - A general part about our style (if any)
  - Tips and tricks (if any)
  - Detailed step by step: again - i would skip this or just link to general docs out on net as our own detailed step by step guide tends to obsolete). That said can imagine a checklist being useful

These are just thoughts but wanted to flag to save you doing ultra-detailed step by step stuff. I also can't emphasize how vaulable a simple tutorial video can be (can just self-record in google hangouts!)

**Comment by EilidhRoss1** [comment]
FIXED all linked to in https://lifeitself.org/tao/communications
