### ISSUE TITLE
Bergerac Praxis Hub Vision post

### ISSUE THREAD

**Issue by khalilcodes** [life-itself/community#285]
Add/update post in lifeitself website before newsletter (Thurs 2022-01-26) from this shared [doc](https://docs.google.com/document/d/1GZh4oWnE_QaFBkqNrciOzAzfLhqKvgcPgq_aQFogYiQ/edit?pli=1#heading=h.zb8rmcbac1og) (written and discussed by Valerie, Marc, Liam and Liubov)

## Acceptance

- [x] Copy from the doc has been posted to the site ✅ **https://lifeitself.org/hubs/bergerac**

## Tasks

- [ ] ...

**Comment by khalilcodes** [comment]
@rufuspollock Liubov reached out via email to me and Nathen about updating the post (shared in description above) on the lifeitself website before thursday's newsletter. Assuming Nathen being out of Office, I believe I can do those changes. To confirm, will this go in https://lifeitself.org/hubs/bergerac ?

**Comment by rufuspollock** [comment]
I don't knowand have not read the doc.

 Generally you should not be posting stuff (you are tech side 😉).

@Liyubov can you clarify what you want and I or @EilidhRoss1 can guide you through this.

**Comment by EilidhRoss1** [comment]
@khalilcodes @rufuspollock I am happy to take on this task and publish what @Liyubov has sent. 
@Liyubov my understanding was that there were also new residencies you were wanting published on the website. Where can I find the information for this?

**Comment by rufuspollock** [comment]
@EilidhRoss1 and before we move on things i think it would be good to get clear acceptance criteria from @Liyubov and team on what they want. And it is best if we can support *them* in posting stuff rather than do it ourselves as empowers them going forward ("teach a person to fish" vs "giving them a fish").

**Comment by Liyubov** [comment]
hi @rufuspollock @EilidhRoss1 thanks for the notes (sorry for answering only now, Thursday I am not rarely checking emails)

for the website we were asking indeed two different things:
1. about publishing information about Life Itself Praxis Hub **now** in January 2023 (thanks for putting it there https://lifeitself.org/sympoiesis @khalilcodes  ) and thanks for help with it @EilidhRoss1 
2, about **future** possible edits for the part of Life itself Praxis hub: if we would need to edit any info about residencies or about hub itself: how it would organised if it would be possible to do it ourselves (just not to bother with small edits questions)? 

thanks!

**Comment by nathenf** [comment]
@EilidhRoss1 was this completed?

**Comment by EilidhRoss1** [comment]
FIXED Content from the [doc](https://docs.google.com/document/d/1GZh4oWnE_QaFBkqNrciOzAzfLhqKvgcPgq_aQFogYiQ/edit?pli=1#heading=h.zb8rmcbac1og) sent by Liubov has been added to the [Bergerac Hub page](https://lifeitself.org/hubs/bergerac) on the site.
