### ISSUE TITLE
New Comms Support

### ISSUE THREAD

**Issue by theo-cox** [life-itself/community#292]
With Eilidh going LI is in the market for new comms support. We have already had 2 expressions of interest to the callout in the newsletter via the hello email. We need to action these, and establish a process and set of terms for this mini-recruitment. Imagine this will be one for some combination of @rufuspollock and @nathenf (depending on his availability) given they're the ones who will predominantly be working with this person going forward. 

## Acceptance

- [ ] Process and terms decided
- [ ] Expressions of interest actioned
- [ ] New comms person accepted

**Comment by rufuspollock** [comment]
I had already opened an issue in ops for this. I think we can delete this one and converge there.

**Comment by theo-cox** [comment]
WONTFIX. Duplicate of ops issue
