### ISSUE TITLE
Create Life Itself WhatsApp Community and consolidate whatsapp groups  there

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#303]
Let's create a Life 

- We have several existing regional and topical groups on whatsapp. 
- WhatsApp communities are now available (Nov 3 2022) https://blog.whatsapp.com/communities-now-available
  - Provides grouping (all related groups in one place)
  - Broadcast messages (useful for e.g. residency announces or newsletter)

## Acceptance

- [x] Life Itself whatsapp community created with e.g. @rufuspollock and @nathenf as admins **✅2023-01-20 by @rufuspollock**
- [x] Add e.g. logo **✅2023-01-20 added default logo**
- [x] Added relevant groups **✅2023-01-20 + 2023-01-31 added all regional and topical groups**

**Comment by rufuspollock** [comment]
@nathenf FYI have created a whatsapp community as per your suggestion in Autumn. atm have made myself and nathen admins.
 
@EilidhRoss1 @nathenf may be worth a note in our comms guide (?)

**Comment by rufuspollock** [comment]
@nathenf do you want to a quick review of how it set it up and then we can close.

**Comment by nathenf** [comment]
@rufuspollock I have reviewed and seen the group now. I guess the next question is how do we use it, but perhaps for another issue. We can close here

**Comment by nathenf** [comment]
FIXED - Life Itself community is now on Whatsapp with all groups consolidated in one place
