### ISSUE TITLE
February Newsletter

### ISSUE THREAD

**Issue by nathenf** [life-itself/community#320]
## Acceptance

- [ ] Newsletter sent out on last week of Feb 

## Tasks

- [ ] Include Whatsapp community

**Comment by rufuspollock** [comment]
@nathenf let's leave this to late feb.

**Comment by nathenf** [comment]
@Liyubov you can add information here for the residencies

**Comment by nathenf** [comment]
FIXED - Newsletter sent out https://mailchi.mp/ae8c312625d0/kicking-off-2022-with-lots-of-action-15509229
