### ISSUE TITLE
Home page and intro lifeitself.org v3

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#335]
This issue is especially substantive as it involves a significant *content* update especially around presenting who life itself is.

https://link.excalidraw.com/l/9u8crB2ZmUo/3moxTTHLUvr

<a href="https://link.excalidraw.com/l/9u8crB2ZmUo/3moxTTHLUvr"><img src="https://user-images.githubusercontent.com/180658/226778898-c8ea8d77-6046-49dc-b18e-04854d82d209.png" height="800" align="right" /></a>

## Acceptance

Reflecting the layout of the page (approx)

- [x] About us summary so that ..
- [x] Portfolio so that ..
- [x] Key ideas / posts so that ...
- [x] ?? Latest (blog filter by topic??)
  - [x] Podcast
  - [x] Blog posts
- [ ] People so that people know who we are
- [ ] Why / story of life itself so that people get a deeper sense of us

### Content

- [x] Capture and clarify existing material (link items, give title, brief description and most importantly anindication of whether useful material to harvest, and what it is) **🚧2023-02-13 by @rufuspollock - made copy of old "copy" doc and started on consolidation at top https://docs.google.com/document/d/1bc17B3nOB2sCGQlKSkNglWPfn47KJeedvKbHn-L8mlw/edit**
- [x] Draft content of front page (e.g. in gdoc) 🚧 **Made a more detailed draft including text in https://link.excalidraw.com/l/9u8crB2ZmUo/3moxTTHLUvr**

### Design

- [x] Wireframe **✅2023-03-10 https://link.excalidraw.com/l/9u8crB2ZmUo/3moxTTHLUvr** 💬 **2023-03-17 Have expanded wire frame with more detail, pending walkthrough on how to intergrate tailwind into obsidian page**
- [x] Mockup **✅2023-03-30 ❌ wontfix - will directly code**

### Implement

- [x] Hero section
- [x] Collaborators
- [x] Latest posts **✅2023-03-30 already done**
- [x] What we're about (vision) **🚧2023-03-30**
- [x] What we do
	- [x] Key writings
		- x ] Reuse our standard BlogCard for keyWritings section
		- [x] 🏆 load key writing info directly from blog post (rather than manual)
	- [x] Create initiatives section
	  - [x] Have a standard InitiativeCard
	  - [x] Load initiative data for key initiatives (or manually hard code for now)
	- [x] Create residencies section

### Existing content docs

- [ ] https://docs.google.com/document/d/1bc17B3nOB2sCGQlKSkNglWPfn47KJeedvKbHn-L8mlw/edit#heading=h.tihkx8p64fi8
- [ ] https://docs.google.com/document/d/1_IO7hrpM9p59WqVnHZd1QBmqbvCzBOjfc9WBkPYzjZg/edit#heading=h.z6dj6ckmkf
- [ ] https://docs.google.com/document/d/1AH81douZ2WAmMAYNC8w1yjVN1hH0Srhe8P2HYeu8IP0/edit
- [ ] https://docs.google.com/document/d/1z2-fXXp2YmGYSVlINY1mGLjuyzlObEWEvyKvPsXhQR8/edit
- [ ] https://docs.google.com/document/d/1d9XVgiE-Uua0DLzQy64Y-DfoY5oaXionMevK1QFXDQE/edit#heading=h.5tzgt6wll1lh
- [ ] https://docs.google.com/document/d/1_2rRVfBuOcZzYoN4lNfTaY2D8KqmZ9x-_kVqMOa5axw/edit

### Content brainstorming

Header:

- Explore the ideas, individuals & organisations creating a wiser, weller world. A multifaceted resource for engaged social transformation. 
- Enter the ecosystem of effective social transformation. 
- The gateway to integral social change.
- Connect the dots of social transformation. Find your community & discover your path. 
- Backed by science, blessed by spirit. Rigorous sensemaking for a wiser, weller world. 
- Your gateway to the world of social transformation.
- Be informed about the state of social change.
- Your portal for effective social transformation.

Subheader:

- Our platform gathers the ideas & actions of emergent social change.
- Our platform makes contributing to & understanding effective social change easier.
- Integrating all forms of social transformation into one accessible & intuitive platform.
- Find your path(s) to effective social transformation. 
- The signpost of inner & outer transformation, you decide the path & we show you the way.

**Comment by nathenf** [comment]
@rufuspollock flagging that I'm blocked here. I've made a more detailed mock up in excalidraw and tried to use tailwind in obsidian but need a bit more of a walkthrough. Maybe we can have a recorded session on that?

**Comment by rufuspollock** [comment]
@nathenf ok and i can help with that (or khalil can). However, before we do that I think a first step (as discussed) was a pure markdown page. We can put this in a pull request so we can review and comment (suggest e.g. `notes/home-new` so we can preview live). We can just use headings to delimit sections and subcards within sections. I think it is worth doing this and really nailing the content before we layout. (the new more detailed mockup is great ... and still lots of content to fill in so suggest we do this markdown version first and then refactor to the design).

## Example of how we can do it

```md

## Key Ideas

### Key Idea 1

Title

Image

Description

### Key Idea 2

etc
```

**Comment by rufuspollock** [comment]
@nathenf i suggest we close this and split out the 2 extra items re adding some of team and the "story" to separate issues (i'd actually split them as one is easy and one is big).

**Comment by nathenf** [comment]
FIXED - New homepage is live at lifeitself.org 🎉  outstanding tasks have been split into new issues #491 and #492
