### ISSUE TITLE
edits for the registration form on April, May residencies

### ISSUE THREAD

**Issue by Liyubov** [life-itself/community#339]
@nathenf  on the website pages:

- https://lifeitself.org/ouroboros-residency
- https://lifeitself.org/setting-the-world-to-rights-residency

people were saying that the link provided to register did not work: 
can it be changed to this one, which works?
 https://forms.gle/WLGpkEkpAY5f1nW46
 
Thank you.

**Comment by nathenf** [comment]
@Liyubov is this fixed?

**Comment by Liyubov** [comment]
no all is fixed, it was not about actually editing website, but about fixing the link, as it was not me who generated the link.

i edited it with new link and all is ok now. 

thank you.
