### ISSUE TITLE
Life Itself people page

### ISSUE THREAD

**Issue by msantolini** [life-itself/community#355]
Hello

A note here to ask how we should integrate the Bergerac Praxis Hub people to the https://lifeitself.org/people page? We had written some [bios](https://docs.google.com/document/d/1skXWzYSYc8RgNJlQysiK4EoDptMvROOEiWODinvUYV8/edit?usp=sharing) some time ago that could be used for this. 

Let me know what you think!

**Comment by rufuspollock** [comment]
@msantolini i think you can just add a section for "Bergerac Praxis Hub" (and Valerie can show up in two places!)

**Comment by msantolini** [comment]
Ok took me a few minutes to reverse engineer the system but I think I went to the right place https://github.com/life-itself/community/commit/027016298e0718f0cc1b1048c5ca129aaf3e0cfa

**Comment by msantolini** [comment]
Hm ok it seems there is a step of cropping and B&W filter that needs to be taken (i thought it was part of the automatic pipeline). Who is the best to assign this? Also Valerie had shared another photo that could be used for her bio, wee in https://docs.google.com/document/d/1skXWzYSYc8RgNJlQysiK4EoDptMvROOEiWODinvUYV8/edit#.

**Comment by rufuspollock** [comment]
@msantolini i think @nathenf @ZybN can probably help ... and agree that we should try and automate this e.g. B&W filter and cropping can be done in css. (@nathenf @ZybN do you want to open a task to a website "inbox" issue)

**Comment by msantolini** [comment]
Also I can't seem to be able to upload files, but in case I did a squared, B&W photo for me.

![marc-santolini-square](https://user-images.githubusercontent.com/956597/224661203-f3645dbe-c8d5-4867-a8ab-6a5a79d3c3cb.jpeg)

**Comment by nathenf** [comment]
@msantolini did you manage to fix this?

**Comment by rufuspollock** [comment]
@msantolini (cc @nathenf) rather than directly solve / answer this i suggest we add this to #379 and then have @msantolini as a tester for the quality of our guide.

**Comment by msantolini** [comment]
@rufuspollock I can't find issue #379 but I basically just need to upload an image to https://github.com/life-itself/community/tree/main/vault/assets/images. Unfortunately I can't do that from the website and get the message

`The following files are configured to be stored in Git LFS and must be pushed using the Git command line with Git LFS installed`

**Can someone who has Git LFS upload the following picture to https://github.com/life-itself/community/tree/main/vault/assets/images ?** I can deal with the rest.

![marc-santolini-BW-square](https://user-images.githubusercontent.com/956597/230307408-73edb8a5-6d5e-4a51-9873-972ce55c3b0e.png)

**Comment by rufuspollock** [comment]
> Can someone who has Git LFS upload the following picture to [main/vault/assets/images](https://github.com/life-itself/community/tree/main/vault/assets/images?rgh-link-date=2023-04-06T07%3A38%3A01Z) ? I can deal with the rest.

@msantolini if you do have git command line installing git lfs is just `brew install git-lfs`. Other option may be to upload file directly on github.

**Comment by nathenf** [comment]
FIXED - People page now updated with new images
