### ISSUE TITLE
Change title on ecosystem mapping back to what we used to have (or better rotating titles)

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#448]
ie. "Mapping an Emerging Ecosystem" or "Metamodern Ecosystem"

Aside: was sure had issue like this somewhere already ...

**Comment by rufuspollock** [comment]
I have changed to mapping an emerging ecosystem.

@khalilcodes can you add info (or even a component) for doing rotating titles ...

**Comment by nathenf** [comment]
FIXED - there is now a rotating title on the ecosystem mapping page
