### ISSUE TITLE
Join a residency button has wrong link

### ISSUE THREAD

**Issue by msantolini** [life-itself/community#464]
The "Join residency" button on the home page should link to https://lifeitself.org/programs instead of the old https://lifeitself.org/upcoming-residencies-gatherings/ which does not exist anymore. In general any link to https://lifeitself.org/upcoming-residencies-gatherings/ in the site should be changed to https://lifeitself.org/programs

**Comment by nathenf** [comment]
FIXED - Updated the homepage link and created a redirect so that anyone navigating to "upcoming" should automatically redirect
