### ISSUE TITLE
Post and promotion for Jonathan Reams talk June 9th 2023

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#569]
Jonathan Reams will be presenting at Research Community Fora on June 9th 2023. He is an expert on developmental theory, editor of integral review, a contributor to Inner Development Goals, and an expert on the Lectica developmental assessment framework. 

Background on this: https://github.com/orgs/life-itself/discussions/435#discussioncomment-5653189 

## Acceptance

- [x] Blog page about the event
  - [x] what, when, register (via zoom[^1]) etc
  - [x] blurb with links about him
- [x] Copy-pasteable text for twitter/whatsapp
- [x] 3pm CET time Friday 9th June
- [x] [zoom link for registration](https://us02web.zoom.us/meeting/register/tZEucuqsqD4qHNy6sJwBY-q56j-3i7sbKE8g)
- [x] shared on SM
- [x] shared with community / events whatsapp groups
- [x] informed John to pass details on to Jonathan and community

[^1]: could we use brevo ...

**Comment by laurenwigmore** [comment]
@rufuspollock 
- I have created an image based on the template in Canva that can be used on the blog post and as needed 
- Tweeted (can't retweet from your account yet based on the access issue noted on my on-boarding issue) and tagged Jonathan and did an IG post - have scheduled a reminder to do this every day until Friday
- Posted in Whatsapp groups (events & community) about the call - will do everyday until Friday
- Drafted email invitation for LI community and 2 reminders in Brevo for those who register - for Thursday and Friday
- Added a comment on the discussion tagging John to share the link and if he needs anything in advance
- Can't find Facebook log in details in Bitwarden for Life Itself 
- Zoom requires a passcode sent to office@artearthtech.com when I try to log in to see who has registered so far, is there a way I can access this email account as well?

**Comment by laurenwigmore** [comment]
@nathenf 
- [ ] Is it worth me sending out an email to the LI mailing list? I have one drafted.
A note on this though - the IG and YouTube links at the bottom of the webinar template don't connect and I couldn't figure out how to amend this

Questions Nathen or @rufuspollock 
- [ ] Who is hosting this on Friday? You? Rufus? 
- [ ] I haven't had a response from John in the discussion that he has informed Jonathan Reams - do we have another way to get in contact with John or Jonathan directly?
- [ ] I can't access zoom to check registrations as I need a code sent, is someone able to check please?
