### ISSUE TITLE
Lack of spacing around page content on small-medium screens

### ISSUE THREAD

**Issue by olayway** [life-itself/community#583]
<img width="752" alt="image" src="https://github.com/life-itself/community/assets/52197250/9052f069-fae7-44d0-a027-b052f273f3f1">

**Comment by rufuspollock** [comment]
@khalilcodes is this an issue in core flowershow or just life itself.

**Comment by khalilcodes** [comment]
@rufuspollock no it's only for jsx pages. Will fix.

**Comment by khalilcodes** [comment]
**Fixed in commit** https://github.com/life-itself/community/commit/c3804ebcaeff0f11f4c69391c30dcdda07490727

<img width="400" alt="Screenshot 2023-06-12" src="https://github.com/life-itself/community/assets/42637597/220ec1b4-896f-43ea-b88d-086bb3e650a3">
