### ISSUE TITLE
Life Itself Labs becomes Life Itself Research

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#592]
After discussion today in research collective we have concluded on naming going forward: **Life Itself Research (Collective)**

This means that we can deprecate and integrate "Labs" into Research.

So! 

> Life Itself Labs is Dead, Long Live Life Itself Research

### Why Research vs Labs?

- Labs is ambiguous: don't know exactly what it does. Is it your experimental projects, your research (lab), a place for innovation etc
- Research is clear term: people know what it is
- Labs is overused: labs is being (over)used all over the space especially in startup space

## Background

https://lifeitself.org/notes/research-at-life-itself-2023

**Comment by nathenf** [comment]
@rufuspollock this has been shared in the newsletter, we also interviewed Marc about this which we could make into a Youtube video and share via blog post. Did you have any other intention for this issue?

**Comment by rufuspollock** [comment]
@nathenf there is a bunch of work to be done i suspect e.g. what happens to labs.lifeitself.org for now? there should probably be a blog post about this for reference and for pointers in the future etc.

Not high priority though (which realistically should perhaps mean just letting this be ...)

**Comment by rufuspollock** [comment]
WONTFIX. At this point, after talking with Jamie Bristow and others, i think we will return to Institute name.

In any case we didn't do anything that systematic in the last year and a half and no reason to do so now.

We did do some things:

- Have the new page at https://lifeitself.org/research
