### ISSUE TITLE
photos upcoming residencies

### ISSUE THREAD

**Issue by msantolini** [life-itself/community#604]
Hello!

I would like some help to change the cover photos for two upcoming residencies:

Long-term residency: 
https://lifeitself.org/programs/2023/long-term-residencies

Maybe we can add this one?

![PXL_20230401_185320946~2](https://github.com/life-itself/community/assets/956597/04f75595-b6e3-4fed-8a42-e4d4def295d7)

Contemplative citizen science
https://lifeitself.org/programs/2023/contemplative-citizen-science

not sure what to put here, do you have an idea on what could resonate here?

in the case nothing comes directly to mind, we could use something a bit geeky like that but i am not a big fan

[EDIT] --> see picture below :)

In addition, is it possible to upload these photos from the hub in a subfolder of pictures in github, for easier future use? https://drive.google.com/drive/folders/1oQK3-3-GGiG-hzoSpYlic-m7cF30ow_t?usp=sharing 

Thanks in advance for the help!

**Comment by msantolini** [comment]
or can use this one for contemplative citizen science

![image](https://github.com/life-itself/community/assets/956597/d651d987-0bb0-44cd-8063-2289afbdfc18)

**Comment by nathenf** [comment]
FIXED - images are updated
