### ISSUE TITLE
Lauren and Nathen Useful Tangents For Reference

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#681]
A place to keep track of ideas and brainstorms currently not directly linked to any issues

## Tangent no.4 2023-07-24

Building a conscious marketing machine
- Creating SOPs for everything
- Integrating AI where possible
	- Mapping the brand voice for consistent tone across content
- Include points of contact with management for review/training
- Conscious marketing includes 3 principles
	- Value focused
	- Audience first
	- Pure Transparency (AKA we use AI, lets say so)
- Ken Wilber 101 course - introduction and overview
 
We are creating a learning portal

- How to do people access what they want?
- Problem: We have multiple different topics on the podcast which need to be collated or curated for people to find what they want

#### Notes
Meeting with digi agency - individual was late, w/o comms - lesson: don't be late and always communicate!

**Comment by nathenf** [comment]
WONTFIX - closing this as not an issue per se and does not have much useful in it
