### ISSUE TITLE
Pop up on website for Conscious Coliving course

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#722]
We would like to add a small corner pop-up to the Life Itself website to encourage new sign ups to the Conscious Coliving course.

We would like the pop up to:
- include the Conscious Coliving header image
- pop up after 5 seconds 
- pop up in the corner
- Header text to include a question - Are you ready to become a Conscious Coliver?
- If people return (stored cookies) don't show again

Can the comms team edit the text in Obsidian/Github once it has been set up? 

## Example

![Sign up for free](https://github.com/life-itself/community/assets/95729108/825fd0fc-eeff-4dc5-8392-3732ae9dd449)

**Comment by olayway** [comment]
@laurenwigmore, @nathenf where can I find the original image file that should be included in the popup?

**Comment by nathenf** [comment]
![Main  Header (1)](https://github.com/life-itself/community/assets/95729108/30ee78e6-5e0b-4a4e-83c6-d468028f21a0)

@olayway does this work?

**Comment by olayway** [comment]
@nathenf Please take a look at the screenshot in the PR and let me know if it looks good to you. What I would maybe rethink is the text, as it's not so clear what is it that we are about to sign up for, i.e. a course.

Also, you mentioned it should show up in the corner, but I don't think this will look good with this particular promo image.

**Comment by laurenwigmore** [comment]
@olayway is there a way we can tweak the text on the pop up as needed? As I agree it isn't clear it is an email course, so it would be good to add that in. Also, thanks for completing this, it looks great!
