### ISSUE TITLE
Community Call with Bella Roberts

### ISSUE THREAD

**Issue by nathenf** [life-itself/community#725]
Community Call with Bella Roberts | 06.09.23 | Topic: Collective Wisdom | Title: How Can Collective Intelligence Enhance Democracy?

## Acceptance
- [ ] Call has been completed and publish on blog and youtube 

### Pre-event 
- [x] Confirm speaker
- [x] Collect and confirm details using [this form](https://forms.gle/mRuG4AWKnrcMH1Q19)
- [x]  Confirm who is hosting/mcing 
- [x]  Add this information to CRM [CRM + Network Database - Life Itself](https://docs.google.com/spreadsheets/d/1JDDIGIU9eluTRs0K5zvkNJKPyc4RWROK7q_ChJTxyT4/edit#gid=1440604079) 
- [x]  Add to the calls tracker github issue #624
- [x]  Create Canva Graphic for thumbnail and featured image using [this template](https://www.canva.com/design/DAFc2iT9fSw/QNjdvOhVKz5P6539L91MyQ/edit)
- [x] Create registration using Zoom (through Life Itself account not your own!)
- [x] Create the blog post 
  - [x] Include image, registration link, biography of speaker or description of the event 

### Pre-Event Promotion
- [x] Notify the speaker once the blog post is live so they can share it with their community
- [x] Email (check the from and reply to is correct) - Use email templates as linked below in the templates section
  - [x] In newsletter (if applicable)
  - [ ] Day before announcement (main group) ⏫Only if the last email or newsletter was more than a 5 days before the event
  - [x] Email reminder day before/morning of (recipients in ZOOM) [watch this Loom](https://drive.google.com/file/d/183Tk1mzTfOV28TPTMoqse-oDEVK_pxtc/view?usp=drive_link)
- [x] List on dandelion events
- [ ] Whatsapp (use image with short text and link)
  - [x] Initial announcement
  - [ ] Day before
  - [ ] 1-2 hours 
- [x] Twitter
  - [x] Thread for initial announcement
  - [x] 3 days
  - [ ] Day before
- [x] Linked In
  - [x] Post initial announcement (use this to create IG stories
  - [ ] Day before post
- [x] Instagram 
  - [x] Post for initial announcement (only image of person not Canva graphic)
  - [x] Stories - create stories by [following this Loom](https://www.loom.com/share/d28d1dd852d64bab81a2b2c753cff521?sid=92769345-7a0b-4492-bd69-460652f9cfb4)
  - [x] Initial announcement
  - [ ] Day before
- [x] Create LinkedIn event

### Post-Event - upload to YouTube and edit main blog
- [x] Make the youtube video 
- [x] Download the video from Zoom
- [x] Trim the beginning and end of the video and the audio to remove any irrelevant sections making sure you split them at the same timestamp
- [x] Upload the video to Youtube
  - [x] Add the thumbnail which you created for the blog post
  - [x] Create the description - Use Otter.ai and read the summaries, or use chat gpt to make summaries and created description from this. 
- [x] Read and double check the reply to make sure it makes sense - this will be used to create the blog post later
 - [x] Use the following framework for the Youtube description:
This conversation is part of a series of bi-monthly community calls hosted in the Life Itself online community if you would like to join future calls join us here: https://chat.whatsapp.com/JNJCTZugNQn1fq89xbHtfA 

#### How Can Collective Intelligence Enhance Democracy?
[summary]
Our democracy is in crisis. The proliferation of disinformation, fake news and now generative AI will make it even harder to know the "truth". In this mired information environment, it is tough to make decisions, especially during election time when we get to exercise the main democratic tool available to us, once every few years. In a deliberative democracy, our voices matter more than our votes. Through deliberation, consensus can be built amongst a shared understanding, trust and empathy. Collective intelligence describes a form of collective decision making, which is being increasingly enabled by technology - allowing people to participate at scale, from any location. However deliberative technologies are soon becoming able to not only summarise, but recommend and predict what we say; therefore blurring the lines of agency between human input, and AI. How can we harness these technologies to empower the people and restore democracy, before its too late? I promise that I wrote this blurb, not ChatGPT.

[about the speaker]
At the start of 2021, my life took a crazy turn when I decided to run for election for the London Assembly, leaving behind a decade in the finance industry. This was the first year that the UK had officially left the EU and we were in the midst of the COVID pandemic with no vaccine rollout plan. Everything seemed highly uncertain, and unpromising, but I wanted to take a stand. Like many others, I did not feel like we had a say and it felt like democracy was broken. Following the experience, I embarked on a Masters in Digital Politics which also had modules in AI and philosophy, leading me to present my main research project to you here today. I also studied the last two terms of my course remotely in Bali - but more on that later!

Photo on Google Form

[chapters]

[usual youtube template which is added automatically]

- [x] add chapters to the description based on the original timestamped summary - If you are unsure how to add chapters watch this: https://www.youtube.com/watch?v=yfEdhlBuxCU 
Add title and description to the Youtube video, this should include:
 - Chapters (timing break down of different sections)
 - Summary 
 - Add to Community Call playlist
 - Add correct hashtags below 
 - Add card to the video at 5 mins linking to the relevant playlist
- [x] Update original blog post with youtube video plus information
 - Title: [subject of call] with [guest speaker name]
 - The content should include, a short description, list the chapters, add about section of the speaker
 - [x] Bella also requested we add a list of the links mentioned in the chat on the blog post
- [x] Update CRM with links etc. [CRM + Network Database - Life Itself](https://docs.google.com/spreadsheets/d/1JDDIGIU9eluTRs0K5zvkNJKPyc4RWROK7q_ChJTxyT4/edit#gid=1440604079)
- [x] Let the speaker know and make it easily shareable
- [x] Delete video from Zoom once you are 100% certain this is uploaded correctly to Youtube - If in doubt keep a local copy on Google Drive

### Post event promotion
- [ ] Announce recording on Whatsapp, Newsletter at end of month, Twitter and Instagram

**Comment by laurenwigmore** [comment]
### Text for Twitter & LinkedIn (set up event):

We are delighted to invite Bella Roberts for our next community call on Wednesday 6th September 730pm CET.

In this call Bella will discuss how we can save our broken democracy. Through the proliferation of disinformation, fake news and now generative AI, it is even harder to know the "truth". In this mired information environment, it is difficult to make good decisions, especially during election time once every few years where we get to exercise the main democratic tool available to us. In a deliberative democracy, our voices matter more than our votes. Through deliberation, consensus can be built through shared understanding, trust and empathy. Collective intelligence describes a form of collective decision making, which is being increasingly enabled by technology - allowing people to participate at scale, from any location. However, deliberative technologies are soon becoming able to not only summarise, but recommend and predict what we say; therefore blurring the lines of agency between human input and that of AI.

How can we harness these technologies to empower the people and restore democracy, before it’s too late? Bella promises that she wrote this blurb, not ChatGPT.

You can register for the call here / through our the link in our bio.

At the start of 2021, Bella decided to run for election for the London Assembly, leaving behind a decade in the finance industry. This was the first year that the UK had officially left the EU and we were in the midst of the COVID pandemic with no vaccine rollout plan. Everything seemed highly uncertain, and unpromising, but she wanted to take a stand. Like many others, she felt that the people had no say and were not represented by those in government. Following this experience, she embarked on a Masters in Digital Politics which included modules in AI and philosophy, leading her to present her main research project to you in this community call.

Bella also studied the last two terms of her Masters course remotely in Bali - but she'll tell you more about that later!

See you on Wednesday!
#communitycall #AI #democracy #fakenews #collectiveintelligence #humaninput

### Twitter thread
1: 
📢 Part 1: Join Us for this weeks Community Call!
🗓️ Wednesday, September 6th, at 7:30 PM CET. 🕢 We are thrilled to welcome Bella Roberts as our guest speaker for our next community call! 🎤 How Can Collective Intelligence Enhance Democracy?

2:
In this digital age, navigating the sea of disinformation, fake news, and generative AI can be like finding a needle in a haystack. 🌊 It's challenging to discern the "truth" amidst this complex information landscape. 🤯

3:
🗳️ Especially during elections, where we exercise our democratic rights, making informed decisions becomes crucial. But how do we ensure we're making the right choices? 🤝 Bella will explore the concept of deliberative democracy, where our voices carry more weight than just our votes. 💬

4: Sign up here bit.ly/3Z2lT4W Wednesday, September 6th, at 7:30 PM CET

**Comment by nathenf** [comment]
@laurenwigmore basically all of the links that were shared in the chat.

**Comment by laurenwigmore** [comment]
FIXED. Hosted and processed.
