### ISSUE TITLE
Checklist for blog posts

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#73]
* [ ] Featured image (why?)
* [ ] Add categories
* [ ] (?) Tags ...

## Categories

* News => used for all real news e.g. launch or major updates to initiatives, partnerships, etc ...
* Events => for events (may also be in news) => so that we can have an `/events/` page run off this ...
* Topics

**Comment by nathenf** [comment]
MERGED with #195 for categories// Checklist blog posts we have here: https://docs.google.com/document/d/1v6HgJEZINhnsxrHamHgZ26Fdc-ee8GWabb8zfbTBCYc/edit?usp=share_link
