### ISSUE TITLE
Landing page for community calls (shall we re-use lifeitself.org/hangouts?)

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#748]
Hi do we have a standard page for our community calls?

I want a page i can link people  to and they can see past and upcoming calls.

Imagine something like e.g. lifeitself.org/hangouts or lifeitself.org/community-calls.

BTW i note that https://lifeitself.org/hangouts already exists and we could repurpose it for what we are now doing ... (to provide some continuity).

## Job Stories

When writing an email to someone I want to tell them about our community calls including how to attend so that they can find out and come if they want

**Comment by nathenf** [comment]
DUPLICATE - see #675
