### ISSUE TITLE
Where can I find community living roommate type sites

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#773]
I am looking to have a house that is more cooperative living. Ideas like group meetings, land plots for growing food if one wanted and a say about what was happening in the house and to the house have been talked about. Maybe even all co-sharing cars and the costs.

My problem is finding the people. I’m also not finding any community living type roommate sites. I’m wondering how to find someone who is looking for this type of living.

## Acceptance
- [ ] There is a page/blog(?) available with related information. 
- [ ] This has also been added to the CC101 bonus content in the course
- [ ] Announced in whatsapp chat 
 - [ ] (and newsletter?)

**Comment by nathenf** [comment]
@laurenwigmore this should be more a discussion thread and we can link to it in the Whatsapp chat then

**Comment by laurenwigmore** [comment]
> @laurenwigmore this should be more a discussion thread and we can link to it in the Whatsapp chat then
MERGED.
I have moved this issue to this discussion thread:  https://github.com/orgs/life-itself/discussions/801 and will close this.
