### ISSUE TITLE
Information on 'a secular monk' - what are the key points to include on the update to the copy for this residency?

### ISSUE THREAD

**Issue by Postnormalval** [life-itself/community#799]

**Comment by Postnormalval** [comment]
after our talk with Liam and Rufus. We want more people  embracing presence and purpose within a light  MVP frame , with core resident for 3 to 6 months and guest from Life itself coming around, doing events but in a light , joyful and emergent way. 
This is not a curated residencies, this is a residency for people who need a spine to feel community energy but have the purpose to use this energy for their own project , having also the possibility to print their project around discussion with other creative and engaged people . 
The documents attached to this proposition are in the google drive https://drive.google.com/drive/folders/1VDNFaxVaRYPuEHGHb3PlAgnORdhEy2XR?usp=share_link

**Comment by laurenwigmore** [comment]
MERGED with #791
