### ISSUE TITLE
Improve website performance

### ISSUE THREAD

**Issue by olayway** [life-itself/community#813]
Our website performance metrics are pretty poor.

## Acceptance

TBD

## Tasks

- [ ] analyse test results
- [ ] ...

### Lighthouse scores

???
<img width="499" alt="image" src="https://github.com/life-itself/community/assets/52197250/063b9822-2380-406c-90ed-c08a49ec69f5">

<img width="500" alt="image" src="https://github.com/life-itself/community/assets/52197250/824809da-b2a6-4cf0-b328-722c906b7cb3">

#### Home page:

Mobile, Chrome, 4G: https://www.webpagetest.org/result/230919_BiDc4Y_9Q0/

<img width="1398" alt="image" src="https://github.com/life-itself/community/assets/52197250/6292caa4-eb15-4b9c-a259-183683893c99">

Desktop, Chrome, cable: https://www.webpagetest.org/result/230919_BiDcVS_A0P/

<img width="1401" alt="image" src="https://github.com/life-itself/community/assets/52197250/f3a484f7-6ba7-4bf1-91ba-4d25e8881046">

#### Blog index page:

Mobile, Chrome, 4G: https://www.webpagetest.org/result/230919_AiDc0P_A4J/

<img width="1402" alt="image" src="https://github.com/life-itself/community/assets/52197250/7e6bf6a6-4d8c-4598-881d-500e8b4aab00">

Desktop, Chrome, cable:  https://www.webpagetest.org/result/230919_AiDcBV_A4P/

<img width="1411" alt="image" src="https://github.com/life-itself/community/assets/52197250/9e1cc2d6-0fe2-45f8-a478-ea175597437f">

**Comment by rufuspollock** [comment]
WONTFIX. For now ...
