### ISSUE TITLE
Q4 2023 Planning (Comms): OKRs + Plan of Work

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#814]
It is now mid Sep. CC101, a content planner, plus a podcast and ongoing community calls were shipped in Q3 2023 and are ticking along. The question is what we do next - we have something of an open field.

This, of course, brings us to the question of overall strategy / direction - our Comms plan should build off that. This suggests a dependency on https://github.com/life-itself/community/issues/196 - or at least greater clarity there.

[Concise summary and overview of agreed strategy and outputs here](https://docs.google.com/document/d/1ALfCTgtS4UFikdfxxyB9Wez08rfNPRajjMdAFst5KlQ/edit)

## Acceptance

- [x] High level strategy clarified sufficiently for this work **✅2023-09-19 we are focusing on building the "sangha" and even just before identifying the "nature" of this sangha and initial ambassadors - what is exactly that distinguishes Life Itself? (What kind of pizza restaurant are we?)**
- [x] Clearly defined OKRs (stored in a spreadsheet) **🚧 90% 2023-09-26 see below. Need to create OKR for community calls (i.e. around the "community" - vs sangha)** [Now tracking in this spreadsheet](https://docs.google.com/spreadsheets/d/1PLycC_qPr156OmGt35FpDsEwrxVZ5XIRrjdYOSaRToA/edit#gid=1004730985)
- [x] High level plan of work (e.g. major initiatives) **🚧2023-09-19 20% just started. ⏭️ is brainstorming the "beacons" we could create** **✅2023-10-05 see milestone with all items https://github.com/life-itself/community/milestone/4**
- [ ] Budget (agreed)
- [x] Write-up of all of this (i.e. Q4 plan) in a way we can communicate to others (both core and more broadly) _link to follow_

### High level strategy

- [x] Review high level strategy https://github.com/life-itself/community/issues/196 **✅2023-09-19 see notes below**
  - [x] Identify best version of this **✅2023-09-19 https://link.excalidraw.com/l/9u8crB2ZmUo/8F30hhvlTcl**
- [x] Identify what is missing in that for this team to move forward (and the needs people have) **✅2023-09-19 had summary from team members. Key missing was identifying where we are focusing in the "rocket ship" building exactly (ans: on building the sangha),  and distinguising our type of sangha**
- [x] Evolve / discuss strategy sufficiently
- [x] Discussion of role of community in particular **✅2023-09-19 we discussed. clarified with various diagrams - see below. People should read Art of Community**
- [ ] Write up document of strategy to present: To include high level strategy (Theory of change, Second renaissance, pockets, our approach)

### Identify OKRs

- [x] Brainstorm
- [x] Finalize ✅ **see below**

### Identify major workstreams

- [ ] Developing beacons
  - [ ] Brainstorm beacons 🚧 **50% we have clear ideas, now need to prioritize**
  - [ ] Finalize attribution of beacon credits
  - [ ] Build the beacons
  - [ ] Promoting beacons
- [ ] Creating "The Week" style toolkit
  - [ ] Brainstorm style and format of toolkit
  - [ ] Build toolkit
  - [ ] Test toolkit
  - [ ] Share toolkit with "ambassadors"
- [ ] Community management and community calls
  - [ ] Reach out to experts to do community calls
- [ ] #568 
  - [ ] #452
  - [ ] Conscious Coliving learn page
  - [ ] Integral Theory learn page
  - [ ] Conscious Parenting learn page
- [ ] Other
  - [ ] Optimize Whatsapp community
  - [ ] Optimize Youtube
  - [ ] Bit.ly link to community from Youtube to track joiners from Youtube
  - [ ] Make a regular invitation to community calls
  - [ ] Maintain tracking of OKRs [Now tracking in this spreadsheet](https://docs.google.com/spreadsheets/d/1PLycC_qPr156OmGt35FpDsEwrxVZ5XIRrjdYOSaRToA/edit#gid=1004730985)
  - [ ] Experiment with Youtube Shorts #588 

---
# OKRs

- Beacons exist and work
  - 10+ beacons created
    - (where course counts as 2-3 credits, a one-off event is 2, a movie is 1, a learn page).
    - Note: Values Jam and EA conversations are not beacon credits. Beacon credit definition tbd.
  - 2000 people attend/engage in beacons
    - with some similar weighting or even a KR per item e.g. 100 people sign up etc)
  - High engagement from a core: X number of (i.e. 20) people do 80% of all beacons.
  - Bonus: [Team formation: ?? 2 teams comes into existence around a beacon e.g. conscious coliving - leave this for now?? enough for Q4]
- Core beacon:
  - "Core beacon" or "toolkit" aka "Making sense of the situation we are in dialogs with toolkit" (intro to Life Itself / intro to what Life Itself thinks is important / intro to key themes / intro the second renaissance) toolkit 
  - 4 runs of the course by different people: Rufus and Lauren plus 2 community members 
  - at least 6 people attend each of these 4 groups for all the sessions.
- Aligned people join Life Itself community
  - join = joining whatsapp group or forum and posting intro message and at least one more time (??)
  - aligned = ?? e.g. assessed by team for now based on their welcome message)
- Refined definition of Life Itself "offer" and Life Itself type person

## Beacon Brainstorm

2x more week long email introductory course 1 for the second renaissance, one for cultivating being:
- Integral Theory 101 + Learn Page
- Permaculture 101 + Learn Page
- Cultivating Being 101 + Learn Page
- Conscious Food 101 + Learn Page
- Conscious Parenting 101 + Learn Page
- Second Renaissance + Learn Page :fire: 
- Community Practices Masterclasses
	- A free but you need to register to view masterclass
  - Victoria from Estate of Mind would like to do a masterclass on IRL UX/UI: Creating functional community spaces
- Films
  - https://www.bfi.org.uk/features/five-films-showing-what-life-commune
  - https://www.ic.org/intentional-community-videos/
- perphaps on creating community (could use bacons book and focus on communication or understanding purpose of community ... sense of belonging) or a deeper dive into a theme that either crosses all three key topics, or conscious coliving as the next step
- 4 week conscious coliving programme:
  - Option 1: We get an expert to run the sessions
  - Option 2: We create a facilitated container rather than a teaching - Emergent Dialogue on Conscious Coliving

### Toolkit Brainstorm

Following "The Weeks" U approach we could make 3 hour long conversations about:

- The Metacrisis
- The Second Renaissance
- Tool and Actions of the Renaissance

---
# September Meeting Notes

## Strategy Summary (for our purposes)

![](https://hackmd.io/_uploads/BkhNkyUyp.png)

- Awakening society comes into being through critical mass in localized areas
- Starts with pockets which over time a) network together b) build a *movement* for change
- Our initial focus (e.g. 5-6y ago) was on these "pockets" i.e. hubs aka "pioneering conscious collectives proximate to the mainstream"
  - However, that was bit early ...
- We are currently focused on steps before that
  - Though o/c pockets are still important - in fact, the most important thing still.

![](https://hackmd.io/_uploads/rkzi_mw1a.jpg)

- Specifically:
  - Creating sangha and especially sangha of shambhala warrior
  - Courses (not the incubator yet)
- Or to get a bit clearer: we want a "Sangha" and that starts with a core and some leaders
  - And essential is what that Sangha is about, what it involves ... who are the people who would want to join.

### How do people shift from one paradigm to the other? Why does density (i.e. pockets matter etc)

![](https://hackmd.io/_uploads/r16q1kL1a.png)

What do people belong to?

### How do we support that transition (and sustained transition i.e. w/o reversion)

Answer: Sanghas and Pockets

- Sanghas
- Pockets

![](https://hackmd.io/_uploads/H11q3kU1p.png)

### What distinguishes Life Itself Sanghas and Pockets (from other Sanghas and Pockets)

Why do you come to "our pizza restaurant" rather than another one.

![](https://hackmd.io/_uploads/H15DGXwyp.png)

### Clarifying terminology

Steps in the transition
- Initiation
- Pledge
- Pockets

---

- Lighthouse, Greenhouse, Clubhouse/Zenhouse
- Second Renaissance
- Shambhala Warrior
- Awakening Society
- Awakening

# OKRs

## Objective

Discover the beacons (i.e. topics, events etc) that attract "Life Itself" type people (in the process iterating and refine that)

What are Life Itself type people? What are they interested in? We don't know exactly. Our rough initial definition:

> people interested/committed to embodied practical action for a second renaissance with primacy of being flavor

Aim at the end to have a short: Intro to Life Itself course that ambassadors could run with e.g. 6-8 people over 6 weeks

## Key results

OKRs

- 10 more beacon credits (course counts as 2-3 credits, a one-off event is 2, a movie is 1, a learn page). Note: Values Jam and EA conversations are not beacon credits. Beacon credit definition tbd. 

- 2000 people attend/engage in beacons (with some similar weighting or even a KR per item e.g. 100 people sign up etc)
  - Finding super member: X number of people do 80% of all beacons. More about a "sharing team"
  - Breakdown of beacon engagement so we can iterate

- X aligned people join Life Itself community (join = joining whatsapp group or forum and posting intro message and at least one more time (??); aligned = ?? e.g. assessed by team for now based on their welcome message)

- "Core beacon" aka "Making sense of the situation we are in dialogs with toolkit"  (intro to Life Itself / intro to what Life Itself thinks is important / intro to key themes / intro the second renaissance) toolkit with a trial with 2 people ("ambassador"?) (as well as Rufus and Lauren) & attendance at live group calls (sense of belonging)
  - Example: https://www.theweek.ooo/about-us
  - Specifically: at least 6 people attend each of these 4 groups for all the sessions.

- Refined definition / clarity on what type of pizza we are

Using welcome group to observe introductions to see if people are Life Itself flavoured. 

What is a better metric than size of Whatsapp group?

- People who are highly aligned with Life Itself (with highly aligned assessed by this team for now)

Belonging is formed in Dialogue, so how do we create more dialogue? 

# Still a big too high level

Top level objective: a flourising self-growing/organizing (in long-run?) sangha of people interested/committed to embodied practical action for a second renaissance

Key results

- Growing membership
- Growing activity (both online and offline)
- Deepening i.e. people taking the vow, joining pockets
- Confirmed exit of Torus to create pockets (Shambhala Ascension 🚀)

Objective: X courses introducing the key ideas and principles and practices of second renaissance, cultivating being, life itself etc

- X courses created
- Y participated

Objective: contribution / participation opportunities and journey

- XX people who are excited and empowered and floursing and resonating with the vision (for themselves)
- Journey created e.g. organizing a local group, ambassadors
  - Create roles: experts, welcomer-s, gardeners (of material), ...
- Y people at stage Z

Objective: Develop authentic and deeply connected Sangha / create leaders or ambassadors to convey the second renaissance and awakening message

- X people carry out initiation
- X people engage in Peer to Peer engagement/mentorship

Objective: membership journey - identification and development of individuals roles/expertise without being the leader

---

Objective (later): start of a movement for a second renaissance emerging out of this sangha and joining with other sanghas

Objective (later): Pockets forming and networking together to form the core of the second renaissance and emerging awakening society.

# Planning Q4 2023

## Review Planned already for rest of 2023

- Values Rally (**Action**: connect in a pilot to CC1010)
  - Why?? Not so clear. More clear if associated ...
- Bi weekly community calls
  - Why:
    - Place for existing / new community to show up
    - Engage existing community (by inviting to calls)
    - Generates a library of relevant content and ideas
- The Great Turning viewing (not rescheduled yet but could be)
  - create a series of things that are useful to consume - read/watch etc
  - position as an intro to second renaissance / Life Itself 101 course (turn into an ambassador pack)
- CC101 blogs and socials - weekly
- Next CC101 initiative MC or 4 week program
- Creative Course - 6 weeks

**UPDATE:** probably cancel values rally.

### Beacons

Courses
 
- Second renaissance (Rufus)
- Conscious food (Lauren + Valerie)
- Conscious parenting (Rufus?)
- Permaculture (Nathen)

Movies + Books

- ...

Events

- Start with a poster and see who signs up

Campfires/hangouts

- Community calls
- Watch a movie
- Book club

### Our 3 core topics

- Conscious coliving
- Second renaissance
- Cultivating being

system for each topic:

- email course
- follow up - set of material to take people through 
- hub week

|  | Email course | 4week zoom | Hub week |
| -------- | -------- | -------- |----|
| Conscious Coliving |          |          |
|  2nd Renaissance        |          |          |
| Cultivating Being       | Text     | Text     |

# Purpose of community calls (discussion 2023-09-25)

- Attractor (mini-beacon) for new members
- Place for new and existing community members to show up (regular touch point)
- Way to engage people (experts) outside the community
- Generates a library of quality, relevant content and ideas (especially re the existing courses) for long tail search
- Shows community is active

Key results

Baseline: Community calls: currently around 10-15 register/attend (slightly less) and less than 100 views on YouTube

- New people show up (how many) and join the whatsapp chat? X new attendees in Q4
- 6 "experts" from outside of our community accept invitation to present
- 700 subscribers on Youtube
- 500 hours of watch time on Youtube
- 50 people signing up to Whatsapp group from Youtube

**Comment by laurenwigmore** [comment]
Nathen and Lauren reflections from a post discussion:
- our community appears to have or be in a more masculine aligned energy 
- the cognitive dissonance between what we are discussing between doing and being.
key Q: **How do you BE in the doing?**

![image](https://github.com/life-itself/community/assets/132304704/ed01e979-0d2a-4205-aa86-6d47c5d5a09c)
![image](https://github.com/life-itself/community/assets/132304704/8cd00c11-7baf-41f4-9a4f-512d4c7e9ded)

**Comment by nathenf** [comment]
Side note: We should reach out to Caroline and others who came a lot and no longer do - ask why

Next Actions: 
- brainstorm the beacons and ideas for what we want to do

Side notes: 
- could create bitly links to see where people sign up from our community (and change all on youtube to monitor number of sign ups/clicks)

Action:
Nathen to break down a call and create some shorts for an experiment

?? Visible offer on major routes on the website (RP note)

**Comment by rufuspollock** [comment]
FIXED. This was pretty much complete plus now superseded by #875
