### ISSUE TITLE
Life Itself Newsletter Nov 2021

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#82]
Draft and send a newsletter for Nov 2021.

## Acceptance

* [ ] Bimonthly newsletter sent out for November 

## Tasks

* [ ] Send email newsletter
* [ ] Report stats (?)

**Comment by rufuspollock** [comment]
@theo-cox i think we can close this. Perhaps share the stats if you would like (%tage opens).

**Comment by theo-cox** [comment]
FIXED. We sent this. Stats here: 
![image](https://user-images.githubusercontent.com/72795023/144208515-41435d00-7b9c-468f-bb71-e29aac587be1.png)
Note significant uptick in opens and clicks (both as a number and percentage) @rufuspollock whoop whoop!
