### ISSUE TITLE
Post up recording with Karl from November community hangout and circulate

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#83]
We have a nice recording of the 7 Nov community hangout with our interview with Karl. We want to post this on our youtube channel and update the blog post.

## Acceptance

* [x] Recording downloaded from zoom and posted to our youtube channel ✅ **See https://youtu.be/CknEw_qNpoQ**
  * [x] Bonus for putting a "title slide" on the front and at the end
* [x] Updated hangout post with embed of video https://lifeitself.us/2021/11/02/community-hangout-november-2021/ ✅ **see #323**
* [ ] (?) Messaged attendees on the calendar event with update **WONT FIX as old**

**Comment by nathenf** [comment]
FIXED - tasks completed with hangout on Youtube and on the blog post

**Comment by rufuspollock** [comment]
@nathenf yay 👏
