### ISSUE TITLE
Bergerac Hub Comms Strategy

### ISSUE THREAD

**Issue by alexianetcu** [life-itself/community#874]
## Acceptance
Devise a sustainable and effective strategy for hub communications, whether it's marketing before residencies to draw people in or during to keep people updated and raise awareness about hub

## 23-10-20 Nathen and Alexia

Situation: We have a physical hub that runs residencies and other initiatives which people can come and join. Participants are currently primarily sourced through word of mouth.

Complication: The residencies/workshops are undersold and this causes strain on the project and the people running it. Finacially there is a thin line between success and failure due to the pricing/business model of the residencies. 

Question: How can we fill the residencies fully and ensure the wider success of the Praxis hub, so that we can continue to develop a wiser, weller world?

Hypothesis: 
- What are the goals of the Praxis Hub?
    - To attract more people to come to the hub
    - To attract people to the broader vision of Life Itself and of the New World, through telling beautiful stories.
- How do we reach more people?
- How do we present offers which are more enticing?
- How do we retain people who come, so that they come again/invite new people? 
- How is the business model set up to ensure contingency finances are available? 
- What is the immediate goal?  Immediate goal is to come up with a plan, but to have a comms plan you need to know what you are selling when and who you are selling it to. 

### Setting up the system and structure for how you will market the next residencies (build the residency strategy)
- Pre-launch: Aim here is to build a email list of hot leads who are interested in the topic of the residency
	- Landing page 
		- How to you build a landing page which optimizes someone deciding to sign-up? What are they looking for? 
		- Promo video/explainer video
	- Create paid advertisements for the free webinar
	- Promote the webinar in groups and social media
- Launch
	- Free Expert Masterclass/Webinar which leads to an upsell 
- Time until implementation
- Actual event (residency)
- Post-event (follow-ups and output from the time sent here)

### Other Marketing Ideas
- Promote residencies in specific groups - use paid advertisements
- Send questionnaires and collect interviews at the end of residencies to be used for research and content creation
https://forms.gle/6vApeLvcjaVYohFp6
- Make a blog post about each residency and promote it

### Building awareness and reputation for the hub (ongoing general stuff)
- Feed whatsapp Life itself with updates
- Increase no. of members of WhatsApp group of France life itself 
- find accounts that share about communal living - study what makes reels go viral and reproduce similar stuff to send to them
- Regular updates on our Instagram especially with collective moments from hub - stories and the occasional posts - mini 1min documentaries showcasing people's experiences
- Newsletter 
- Tenzo Notes - rename them maybe smth like "Reflections from conscious coliving" and make them into a pdf booklet
- Make WordCloud from post-residency questionnaire 
- Maybe video from personal testimonies

## Tasks for next days
- [ ] Read: A guide for storytellers - An initial attempt to create a guide for a volunteer in the hub to create content during residencies. https://docs.google.com/document/d/1EpdCC2xKv3KpNIy5lsA66M4NI5kTxY5r7SrHH7lp-bc/edit#heading=h.fjni2rxtfn47 
- [ ] experiment with creation of reels around daily routine, communal care etc.

### Marketing

- Promote residencies in specific groups - use paid advertisements
- Take photos and videos at key moments - after asking people (consent form to be included in hub terms and conditions)
- Send questionnaires and collect  interviews at the end of residencies 
https://forms.gle/6vApeLvcjaVYohFp6
- Make a blog post about each residency 

### General Comms strategy ideas for coming months

- Feed whatsapp Life itself with updates
- Increase no. of members of WhatsApp group of France life itself 
- find accounts that share about communal living - study what makes reels go viral and reproduce similar stuff to send to them
- Regular updates on our Instagram especially with collective moments from hub - stories and the occasional posts - mini 1min documentaries showcasing people's experiences
- Newsletter 
- Tenzo Notes - rename them maybe smth like "Reflections from conscious coliving" and make them into a pdf booklet
- Make WordCloud from post-residency questionnaire 
- Maybe video from personal testimonies

**Comment by alexianetcu** [comment]
Valerie's input on Comms strategy for now:
- strategy to market residencies broader to be put on hold until trustees Board meets and assesses priorities and whether that's needed given the ability for their networks to fill our spots. Comms efforts will then likely be targeted to their networks who will become ours, instead of general promotion.
- Something Alexia should work on instead is to document (in writing and also visually) the impact and affect of our practices, to prove we are a transformational space, which could also be used to access funding down the line. The first steps of this documentation is to gather information from the post-residency questionnaires and devise a process of analyzing the data (presenting it visually like in a WordCloud would be an option), as well as compile videos and pictures that document both the practices and people's transformation.
- As many participants highlighted a need for highlighting our unique system of integrating food into conscious community, we will also think about different ways of promoting that more.
@rufuspollock @nathenf what do you think?

**Comment by laurenwigmore** [comment]
My two cents 😄  Paid ads could be something to consider as well later down the line - google ads and/or IG/FB - you can play around with audience type and 'copy' audiences as well, and have a cost cap. Although ads would only really be supported if a number of the above actions were implemented first to showcase the Hub more.

**Comment by nathenf** [comment]
@alexianetcu regarding using facilitators networks to fill the spots that is great, but does nothing to build sustainability of praxis moving forward. I would still suggest using the Free Webinar to build a mailing list for Praxis. This is how other peoples network becomes the Praxis network

**Comment by laurenwigmore** [comment]
@alexianetcu can you provide an update in the main issue of where you got with this based on the conversations please

**Comment by rufuspollock** [comment]
WONTFIX. This never really got worked on.
