### ISSUE TITLE
Website Display of Current and Previous Residencies  

### ISSUE THREAD

**Issue by alexianetcu** [life-itself/community#876]
This issue is about residencies from April 2023-present moment not showing up in the previous residencies section of the website.

## Acceptance

- [x] gain understanding on why some of the 2023 residencies disappeared off the index/"previous" section once their starting date passed **✅2023-10-25 residencies from April 2023 and before are hard-coded on the page. And for residencies there was no code to automatically display them. Furthermore, we also had it that residencies go into the past once they start which doesn't work for the current residency which is an "open" one ...**
- [x] restore the missing residencies along with their descriptions to the index **✅2023-10-25 done - see commit and site**
- [x] ensure that going forward residencies automatically pass into "previous" section upon ~~starting~~ ending and that otherwise are in the main residencies section **✅2023-10-25 see commit and site**
- [x] create a section for "current residencies", in which to put the Fall long-term one, as we still are open to people applying for it. **✅2023-10-25 ❌ just have one section for current and future residencies**

## Notes
Situation: Currently in the previous residencies section (AKA the index - https://lifeitself.org/programs), there are only the residencies until April 2023, see screenshot: ![image](https://github.com/life-itself/community/assets/145260066/8a1d38eb-23f8-463a-90d3-3e5bf5507d40)
I located where in Obsidian the pages of the residencies since then are (but they are in their complete form - not succinct in order to fit the "previous" section style):
![image](https://github.com/life-itself/community/assets/145260066/f6be6d96-9878-4811-8891-3dc6e66f0692).
Important to note that that means these residencies are still on the website, eg. at https://lifeitself.org/programs/2023/long-term-residencies, BUT they are not listed in the index page at https://lifeitself.org/programs, **which means that people who go on our site can't find them unless we share the specific link with them.**

Complication: We want all the spring and summer  residencies up in the index, and ideally a "current residency" section in which to put the Fall one.
I cannot figure out how to migrate them to the "previous" section in the succinct form, and how to ensure this happens automatically from now on.

Question: How does one put previous residencies' descriptions into the index and also maybe automatize their transfer into the that "previous" section, so that this does not happen again?

Hypothesis: There is a malfunctioning automatic plugin that sends residencies to archive once start date passes, or there is another folder in Obsidian (which I didn't find) in which past residencies must manually be input in.

**Comment by alexianetcu** [comment]
@rufuspollock @olayway 
Please let me know whichever of the hypotheses is correct and how we can fix this as soon as possible.

**Comment by Postnormalval** [comment]
just to flag that the current one has also disappeared

**Comment by alexianetcu** [comment]
Yes, would be nice to create a section for "current residency" when we are doing the longer-term ones.

**Comment by rufuspollock** [comment]
@alexianetcu please in the issue can you link to and/or provide screenshots of what is not working e.g. on this page ... there should be X (screenshot).

Minor points: let's not assign lots of people to an issue. Right now let's assign this issue to you and you can @ me in the comments to get help ...

**Comment by rufuspollock** [comment]
To note the residencies are on the website e.g. https://lifeitself.org/programs/2023/long-term-residencies but they are not listed in the index page at https://lifeitself.org/programs. Summarizing that point in the main description would be helpful ...

**Comment by alexianetcu** [comment]
@rufuspollock updated with your input

**Comment by rufuspollock** [comment]
FIXED. See https://github.com/life-itself/community/commit/076152341ea5b4ee28b9b62af353bb52c16afd20

**Comment by alexianetcu** [comment]
@rufuspollock wanted to let you know that the edits made to the programs page yesterday didn't go through, see:
![image](https://github.com/life-itself/community/assets/145260066/7d3a4c69-556b-414b-843c-5b2b6f98e434)
Could you try pushing them through again?

**Comment by alexianetcu** [comment]
@rufuspollock just checked again and it's all good now.

**Comment by alexianetcu** [comment]
FIXED. Closing issue as webpage is now as desired.
