### ISSUE TITLE
Follow on(s) Courses to CC101: Shaping

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#879]
Identify and shape a CC101 follow on(s).

Appetite: The content should be able to be shipped (including launch and initial marketing) in 6 weeks or less.

[Coggle Diagram](https://coggle.it/diagram/ZUj97CcP9Medbsqw/t/-)

## Motivation

After a broad and grounded introduction into the wider topic of CC, 

- extend on what we have already written
- provide deeper, new knowledge
- that is practical or has some practical application
- inspires action
- that naturally funnels into a live course and later a visit to one of the Hub residencies

## Acceptance

- [ ] A shaped pitch for 1-2 email courses

Shaped is as per ...

> 1. Problem — The raw idea, a use case, or something we’ve seen that motivates us to work on this
> 2. Appetite — How much time we want to spend and how that constrains the solution
> 3. Solution — The core elements we came up with, presented in a form that’s easy for people to immediately understand
> 4. Rabbit holes — Details about the solution worth calling out to avoid problems
> 5. No-gos — Anything specifically excluded from the concept: functionality or use cases we intentionally aren’t covering to fit the appetite or make the problem tractable

For us a shaped solution would be a description of the kind we could share with others plus rough skeleton (ie. one-two sentences about each session with some sub-bullets for content)

Sub-items

- [x] Research on options including feedback from current participants and community
- [x] Shortlist and selection

### Prep research

- [x] Review feedback from CC101 course https://docs.google.com/forms/d/1crMbM1RqdOUa2sFVJA958BXZgwVb47BHksoH2azvncQ/edit#responses
- [ ] Collect insights from talking to people who did the course or who are interested
- [x] Do a short survey (may depend on having some ideas to offer)
  - [x] Create a short survey for email and whatsapp ✅  _see below for results_
  - [x] email short survey to current cc101s for what do you want to see next
    - [x] Also on whatsapp group
- [ ] follow up with cc101 feedback form for higher responses
- [ ] Review existing offerings out there e.g. FIC etc
- [ ] What is the user journey people are on that this contributes to **✅2023-10-25 see notes below**

### Brainstorm ideas

- [x] Brainstorm initial ideas **✅2023-10-25 see below - may get more**
- [x] Write short pitches (one sentence or two for sharing in the surveys) "Emotional intelligence for conscious coliving"
- [x] Shape 1-2 top options

### Journey people are on

What's the journey people are on?

What interests / needs do they have?

Lauren summary from talking to people so far

> "People know how they are living is not in alignment with how they want to live" ... they found the course and it's given them good insight ... but they don't know how to navigate the practicalities of it ... and the *concrete* next steps"

- Lurkers / Potentially interested: People know how they are living is not in alignment with how they want to live
- Explorers: Interested a bit: want to find out more
- Want to take *some* steps / dip toe in the water
- Trialling
- Changing their lifestyle: either joining or setting up conscious coliving
  - Could be big or small change (e.g. joining a conscious coliving community or evolving their flatshare to be "conscious")

### Brainstorm

- How to make your (existing) coliving situation more conscious
- "Dipping your toe in": How to take the first steps towards conscious coliving and see if it is a fit for you
  - "Conscious Coliving in Action: Practical Steps to Getting Started with Conscious Coliving" 
- "Putting the Conscious in Conscious Coliving": how to become more conscious so that coliving works and how coliving helps you become more conscious.
   - Emotional Intelligence for Conscious Coliving 
  - Coliving means relationships Yay. And both the positives of that e.g. friendship and people to hang out with and the challenges e.g. conflict. Managed well conflict can be one of the biggest opportunities for growth etc etc.

NB: could merge first two together.

### Feedback from CC101

It was a really excellent overview of conscious coliving 101. I had assumed/hoped it might go into a bit more detail of things like governance models or practical examples/case studies of different types of communities or approaches to resolving conflict. Maybe you could create a more in depth version for those who have finished the course and are hungry for more!

Some short videos, more consistent text formatting (same font and size of text all the way through, except titles obivously), ask more questions, or lave spaces for personal reflection to allow information to be processed

I suppose a smoother, more direct path to whats next. You learn all this cool stuff and then its like "we have residencies" (where is this place located in the world? and join our newsletter (i would re-plug whatsapp community here.

I would guess theres 3-5 things people want after this course as next steps. For me, its "find communities to visit or join" or "find others to explore starting a conscious coliving situation with" You'll know the 3-5 better than me. How about 3-5 more courses (paid maybe)? Or direct next steps for each one. Or a direction to whatsapp group for each? A video to an interview with someone living in a CC situation? You'll have better ideas than i.

Overall, the transition for theory and learning to action is what would make this even hotter.

I’d like some help understanding how to find coliving opportunities, how to determine in advance which configuration would be work for me, and how to consciously experiment toward a situation that works best for me.

### Ideas

- Questions: what do people actually want to know? Where are they stuck? What are the sticking points? What information shifts the needle to ensure we are creating/supporting the awakening nature and bringing CC into the awareness that this is needed/important in the second renaissance and paradigm shift.
- Relationships - conflict / communications / empathy
- How to set up a CC or re-align a current space
- CC in a city / urban landscapes
- Practices to support CC 
    - conscious raising practices - individual and group 
    - practical aspects of coliving (key issues i.e. washing up / finances)
- can we link into something from the DDS research?
- sense of belonging 
- use of MVPs into a practical application - knowledge insight from the Hub / Hub set up as a basis
- Practically how to manage a CC 

## Poll results 
Whatsapp & email as of 31st Oct 
After CC101 I really want to an email course on . . .
- Conscious Coliving in Action: Practical Steps to Getting Started with Conscious Coliving: 15
- Conscious Coliving Relationships: How to strengthen & develop conscious r'ships & manage conflict: 8
- Emotional Intelligence for Conscious Coliving: Understand how to navigate the ups&downs of CC: 18
- Other: I have another suggestion which I'll add below: 1 
 _I'd love all of the above topics. And in case it's not specifically included: collective finances & projects, collaborative decision making, governance, how to choose your "co-livers" and become a well balanced group._

**Comment by laurenwigmore** [comment]
@rufuspollock I've drafted the [pitches here](https://docs.google.com/document/d/1KnTnA4MBjzI46Ex4Duz2s6SGbAwXQfhrUPiC2HKpdTI/edit). I'll send you a calendar invite for a Thursday PM meeting if you have a chance to review before so we can discuss and move forward. If not I'll be next available on Monday 6th.

**Comment by laurenwigmore** [comment]
> @laurenwigmore to note: we had the meeting last week and refined the two pitches and likely focusing on the "Constructive Conflict" (or "Nourishing Conflict" or "Transforming Conflict into an Opportunity for Growth") ...
> 
> @laurenwigmore can we finalize the two pitches and post them (separately) in the discussion forum in the ideas section for comment and then we can close this.

Sure no problem will do this morning. I've put the conflict one into a coggle and was looking into that a bit more. I'll put the other one into a coggle as well.
