### ISSUE TITLE
Develop a landing page for Conscious Coliving and connect relevant offers

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#881]
In Q4 (and beyond) we have decided to make conscious coliving a key workstream that interlink our current offers and new offers we will develop. 

We need to have a core landing page for Conscious Coliving and this should be linked to our homepage with high placement, so that people can easily navigate to our most active initiative.

## Acceptance

- [ ] All current offers assessed for relationship to conscious coliving and recommendations out of that for changes
- [x] Landing page created for conscious coliving 🚧 https://lifeitself.org/conscious-coliving basic wireframe of content create, but needs work on buttons and design see https://www.canva.com/design/DAF0NW4nRlQ/dLTswyWRgLtP6ZVXoJQV4g/edit  **✅2024-01-16 landing page was created a while ago - and is ok. Could, of course, do with improvements.**
- [ ] Sharing

## Plan of work (in progress)

- [ ] Conscious Coliving terminology used wherever appropriate
- [x] Page explaining: CC, DDS and residencies fit together ✅ https://www.canva.com/design/DAF0NW4nRlQ/dLTswyWRgLtP6ZVXoJQV4g/edit 
  - [x] A single excellent entry point for CC at lifeitself.org
    - [x] Introduction
    - [x] Links to course/s
    - [x] Link to the Whatsapp Channel
    - [x] What is Conscious Coliving
    - [x] Why is it Important? (link to theory of change & broader context)
    - [x] Our approach
    - [ ] Include all relevant blog posts 🚧 just a basic link to the blog rather than showing the category directly on this page
- [ ] Interlinking page with other pages
  - [ ] Mention in course
  - [ ] In relevant community calls
  - [ ] Blog posts
    - [ ] Link to main page on relevant blog posts @moonimmisch _(notes in comments below 2023.12.12)_
    - [ ] Add conscious coliving category to relevant community calls @moonimmisch 
  - [ ] Landing page of Life Itself rejigged
    - [ ] Add conscious coliving page call to action near the top

## Current Offers

- Residencies (AKA come try conscious coliving) 
- Community Calls (AKA learn about conscious coliving together)
  - All ongoing calls are directly relevant to conscious coliving and will be added as context for the calls 
- Conscious Coliving Course (Self-directed learning)
  -  And CC201 on the way 
- Learn Pages (Self-directed learning) 
  - Currently not directly linked to CC, however both Cultural Evolution and Fundamental Wellbeing are relevant and need to be linked
- Ecosystem Map 
  - Currently focused on organisations mostly (Although La Matrice, Findhorn would potentially fit into CC) 
  - Easiest approach would be to add Conscious Coliving as a tag/topic and integrate a few more organisations

## Conscious Coliving page

**Hero Image + Header** - Conscious coliving: A way of living to thrive not survive // Living together in conscious communities is a concrete practical action to enable personal, collective and societal flourishing. // [New to Conscious Coliving? Start Here](https://lifeitself.org/conscious-coliving-course)
 
 **Introduction** What is Conscious Coliving?
 
 Video instead of text would be good here. See video script below. 
 
 **Offerings** Learn About Conscious Coliving
 - Conscious Coliving 101 
 - Transforming Conflict in Community
 - Practical Steps Toward Conscious Coliving 

**Whatsapp Group** The online community for Conscious Coliving // Join 100+ other curious conscious colivers to learn, share and connect in a simple, easygoing way. No thrills, just a chat channel! 

**Why is it Important?** 

At the core of Life Itself's Theory of Change, is that for us to step into the new paradigm we must create seeds for the Second Renaissance. These seeds are cultivated from physical spaces where people can connect deeply and innovate social, spiritual and practical elements for the next paradigm. 

Conscious coliving is therefore fundamental to seeding the Second Renaissance. By living together we are actively and consciously working on our personal, interpersonal and collective development. 
 
**Our approach** 4 icons for Education, Research, Practice, Support 

Education: Resource building around conscious coliving through courses, interviews, community calls and articles. Start with the Conscious Coliving 101 course. 

Research: Our work on Deliberately Developmental Spaces delves into the ideas, methodologies, tools and establishments that are fundamental to the paradigm shift. This includes coliving spaces, educational institutions and other organisations. Read the manifesto here: https://developmentalspaces.org/ 

Practice: The Bergerac Praxis Hub, is a space for people to experience conscious coliving in action. While the residencies cover many topics at its core is the fact that attendees will live in community together for at least one month. This is a fantastic opportunity to try out conscious coliving (especially with people you might want to live with in the future). Learn more: https://lifeitself.org/hubs/bergerac

Support: The Life Itself community is a growing online community of people interested in conscious coliving and more generally creating a wiser, weller world. There are opportunities to connect with like-minded people, have your questions about conscious coliving answered and join regular community calls about conscious coliving. Learn more: https://lifeitself.org/community
 
**Explore More** Read our blog posts and watch past community calls about Conscious Coliving

## Video Script

When you hear conscious coliving, what might spring to mind is a group of people all living together under one roof, sharing everything they own and living outside of society. While this is one potential example of conscious coliving, it can be vastly different than this too. 

Let's begin by breaking down conscious coliving to define its separate parts. 

Conscious, consciousness: Aware of and responding to one's surroundings; awake.

For us consciousness has two elements: 1. An active engagement with inner development whether in a spiritual or secular form and 2. An explicit awareness of one’s impact on others and the planet. 

The path of consciousness is seeking greater levels of awareness. 

Coliving: The practice of living in a space with 2 or more other people 

Modern coliving is where people live together with varying degrees of integration and shared space.

This covers the broad spectrum of co-living models, from one where all space is held in common to one where everyone has their own private, personal dwelling along with some shared communal spaces such as a kitchen or a dining area. It can also range from a fully residential model to short-term retreat style approach and much in between.

One important point for us, is that we see co-living as not simply being an economic convenience but involving an active commitment to fostering community.

## Job stories
- I want a single page where I can understand Conscious Coliving and how it relates to Life Itself
- I want to know what actions I can immediately take 

### A Multidimensional Approach to Conscious Coliving: Education, Research, Practice, Support 

While being more connected than ever, we exist in a society that is oftentimes isolating and polarising. Media sensationalism, propaganda, fake news, viral video content and the algorithms that determine success by level of attention rather than intention have set us adrift from consciousness and connectedness. 

The nuclear family unit has been decayed and replaced with technology and individualism. Technology is the new god, who people pray to with their mobile phone between their palms. Yet many of us are fed up. We're ready to take back our power and stand united as resilient families and communities. 

Change is afoot, and there is a growing movement of people seeking to regain the power of living in true community - Conscious Colivers. 

### What is Conscious Coliving? (Taken from course)

Before we define conscious coliving, we need to first understand what these two terms mean independently.

#### What does it mean to live consciously?

To be conscious you need to have an awareness of an internal and external existence. To have both knowledge and be able to respond (instead of react) to your surroundings. Therefore, for us, conscious living has two complementary components:

An active engagement with inner development whether in a spiritual or secular form
An explicit awareness of one’s impact on others and the planet

#### What is coliving? 

Modern coliving is where people live together with varying degrees of integration and shared space.

This covers the broad spectrum of co-living models, from one where all space is held in common to one where everyone has their own private, personal dwelling along with some shared communal spaces such as a kitchen or a dining area. It can also range from a fully residential model to short-term retreat style approaches and much in between.

One important point for us, is that we see coliving as not simply being an economic convenience but involving an active commitment to fostering community.

All of the below, and more, can be examples of coliving environments:

- Living with your family
- Living with your partner
- Your street
- A house share
- Your village
 -Intentional communities

So, conscious coliving is the joining of being conscious within a coliving environment. We see these two aspects of conscious coliving as complementary and synergistic. That is, conscious living supports coliving and coliving supports conscious living.

### Our Multidimensional Approach

We believe conscious coliving is fundamental to personal, collective and societal transformation. We are dedicated to making conscious coliving research mainstream adoption. 

Here is why: 
- Living in conscious community offers the greatest opportunity for people to experience fundamental wellbeing due to the need to work with ones shadows (the fabric that ties you to individualism and isolation) and the ability to find accountability from other conscious colivers. 
- Conscious coliving environments are vital for the innovation and collective action from a values-based approach.
- Communities dedicated to conscious coliving will be the seed locations for the Second Renaissance enabling the paradigm shift to a wiser, weller world. 

We approach the advocacy and adoption of conscious coliving through four unique streams of work:

#### Education 

Resource building around conscious coliving through courses, interviews, community calls and articles. Start with the Conscious Coliving 101 course. 

#### Research 

Our work on Deliberately Developmental Spaces delves into the ideas, methodologies, tools and establishments that are fundamental to the paradigm shift. This includes coliving spaces, educational institutions and other organisations. Read the manifesto here: https://developmentalspaces.org/ 

#### Practice

The Bergerac Praxis Hub, is a space for people to experience conscious coliving in action. While the residencies cover many topics at its core is the fact that attendees will live in community together for at least one month. This is a fantastic opportunity to try out conscious coliving (especially with people you might want to live with in the future). Learn more: https://lifeitself.org/hubs/bergerac

#### Support

The Life Itself community is a growing online community of people interested in conscious coliving and more generally creating a wiser, weller world. There are opportunities to connect with like-minded people, have your questions about conscious coliving answered and join regular community calls about conscious coliving. Learn more: https://lifeitself.org/community

**Comment by rufuspollock** [comment]
@nathenf am i correct this is the main issue you are focusing on atm ...

**Comment by rufuspollock** [comment]
@nathenf and from discussion: main focus is sketching out a new consolidated landing page - e..g lifeitself.org/conscious-coliving - probably also some update of the front page.

**Comment by laurenwigmore** [comment]
@nathenf is this done now?

**Comment by nathenf** [comment]
@laurenwigmore it is incomplete, I have updated with what I have done

**Comment by laurenwigmore** [comment]
@moonimmisch can you spend some time going through and updating the blogs and relevant community calls (webpage and Youtube description) with a link to our conscious coliving page please? Feel free to send me the sentences on whatsapp to sign off - we can keep them simple and to the point, but enticing. i.e. want to learn more about conscious coliving? visit our dedicated page here [hyperlink]. 
(These are the 2 items above I have added a tag next to)

**Comment by laurenwigmore** [comment]
> @moonimmisch can you spend some time going through and updating the blogs and relevant community calls (webpage and Youtube description) with a link to our conscious coliving page please? Feel free to send me the sentences on whatsapp to sign off - we can keep them simple and to the point, but enticing. i.e. want to learn more about conscious coliving? visit our dedicated page here [hyperlink]. (These are the 2 items above I have added a tag next to)

@moonimmisch can you also keep track of the links you've updated in a spreadsheet in the conscious coliving folder please

**Comment by laurenwigmore** [comment]
@moonimmisch can you update the tasks above with what you've actioned please?

**Comment by rufuspollock** [comment]
FIXED. For now let's say this is done. Let's do a proper quick shaping of this work and identify next steps from that.

@moonimmisch please can you still share where you have got to with your tasks here asap (/cc @laurenwigmore )

**Comment by moonimmisch** [comment]
@rufuspollock @laurenwigmore The link to the landing page has been added to all relevant blog pages on the website & also to any youtube video descriptions I deemed appropriate. See spreadsheet: https://docs.google.com/spreadsheets/d/1Oz09uehrtQLes6-W2oRklbMSUN4v6JYCqeT1krNWBIE/edit#gid=461168992 

I believe all the tasks assigned to me on this are completed but happy to do anything else if needed!
