### ISSUE TITLE
Share polished Fundamental Wellbeing page

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#901]
Now we have completed #870, let's share it so people find out about it !

## Acceptance

- [x] Short blurb

### Promotion - Phase 1 

- [x] Shared on Finders community telegram (Rufus has access) **✅2024-07-10 - did this yesterday**
- [ ] Martin's shares (where?)
- [x] Life Itself SM: Twitter, 
- [x] LinkedIn, 
- [ ] Facebook, 
- [x] Instagram
- [x] Newsletter
- [ ] Reddits, FB groups (FWB one as well?)

### Promotion - Phase 2

- [ ] Create 5-10 video clips from the interviews which we can store and use through the year to promote the page, once per month

#### Blurb 

**Tweet 1** 

Can you do rigorous empirical, actionable research into awakening? Turns out you can. We interviewed Dr. Jeffery Martin for hours, read his work and distilled down the key insights of his 15 years of research. 

👉 https://lifeitself.org/learn/fundamental-wellbeing

**Tweet 2**

"65% of people experience awakening in 6 weeks", a bold claim from Dr. Jeffery Martin who has spent over 15 years researching awakening and how it occurs and helped thousands reach it. Check out multi-part interview and summary of his work.

👉 https://lifeitself.org/learn/fundamental-wellbeing

**Longer Blurb**

Awakening or enlightenment aka fundamental wellbeing is one of humans greatest endeavours. However, it's difficult to reach. No surprise given its often unclear what it even looks like plus there are a bewildering range of techniques whose (in)effectiveness is largely anecdotal.

Enter Dr. Jeffery Martin. Over fifteen years ago he dedicated himself to exploring the further reaches of human wellbeing in a rigorous, empirical way. He has interviewed hundreds of people who have claimed to reach enlightenment, analysed the data and created a three month protocol that has enabled thousands of people to attain Fundamental Wellbeing with a claimed 65% success rate.

Check out this multi-part interview series and detailed introduction to his work:

👉 https://lifeitself.org/learn/fundamental-wellbeing

#### Reddit Text 
_checked by Lauren ✔️_ @moonimmisch 

Hey guys!
I came across a fascinating interview series with Dr. Jeffery Martin, who's spent 15 years exploring the depths of human wellbeing, that I thought the members of this group would find interesting. I have been interested in Dr. Jeffery Martin’s work for a few years now and I found this a great introduction to his research, especially if you're new to it. Is anyone else familiar with his work? Or have any other references they could share for me to dive in to more of? I find this topic fascinating, and am avidly on my own transformational journey to see how I can really support my own 'fundamental wellbeing' and enhance my life. Looking forward to hearing more from others. Oh and the interview link for those who might be interested: https://lifeitself.org/learn/fundamental-wellbeing

N.B. (there might be some groups where links aren't allowed in which case reference the website and page without linking)

**Comment by nathenf** [comment]
@rufuspollock did we hear back again from Jeffery?

**Comment by rufuspollock** [comment]
@nathenf not yet - and about what? As i wrote in [comment](https://github.com/life-itself/community/issues/870#issuecomment-1808239987) about this you asked last week:

> @nathenf i took his response as a 👍 for the piece - and simply that he was going to share once on the road. if unclear, why don't you just double check in the thread (i.e. something like "are you happy with page content? we wanted to check before we shared ..."

Let's get moving 😄 - and in any case we should definitely share now with him a sample text or two he could use to share on social media (with obvious point that he can tweak as he needs!)

**Comment by nathenf** [comment]
Hey @moonimmisch, 

So I've created some blurbs in the issue here which can be used to share on socials, I have not yet shared on any social media or in any reddit groups. It went out in this months newsletter. 

Therefore, next step is to share on socials and maybe @rufuspollock you can share in the Telegram?

**Comment by laurenwigmore** [comment]
@moonimmisch in the New Year could we also create some 60sec shorts from the interviews, and potentially use an adapted version of Nathen's tweets in the promo? Might need to be a case of reviewing the transcript (over watching the videos from a time perspective) - can you add this as something for us to discuss more please in January.

**Comment by rufuspollock** [comment]
@laurenwigmore at this point - since this is something worth adequately promoting i suggest we aim for late Jan/early Feb.

**Comment by laurenwigmore** [comment]
@moonimmisch 

> [@moonimmisch](https://github.com/moonimmisch) in the New Year could we also create some 60sec shorts from the interviews, and potentially use an adapted version of Nathen's tweets in the promo? Might need to be a case of reviewing the transcript (over watching the videos from a time perspective) - can you add this as something for us to discuss more please in January.
> 
> * I've also tagged you in a document so you can see the templates Nathen and I used in CC101 promo in groups

@moonimmisch let's focus on creating some 30-60sec shorts for this. Let's have a chat on Wednesday 24th to arrange this and be clear on next steps.

**Comment by rufuspollock** [comment]
FIXED. Done what we can for now. There's a specific task around this for testing out social media help in #1079
