### ISSUE TITLE
Check this AET glossary is merged into the tao

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#92]
Check this AET glossary is merged into the tao - https://docs.google.com/document/d/1b-9B3b-rEtpYqw5fCXCs0CcoUIuBBmuhwmJ5IfsvgSI/edit#heading=h.nj7mfrmxnynh

Add to https://lifeitself.org/notes/glossary

**Comment by bilalshaikh292** [comment]
heyy,
@rufuspollock is the issue still open ?can i work on the issue?

**Comment by rufuspollock** [comment]
@bilalshaikh292 yes you can still work on this.

**Comment by bilalshaikh292** [comment]
@rufuspollock i cant get the access to drive and also can you provide me a little help?

**Comment by bilalshaikh292** [comment]
heyy @rufuspollock i still cant access the drive?

**Comment by rufuspollock** [comment]
@bilalshaikh292 did you see my comment here https://github.com/life-itself/community/issues/112#issuecomment-1236273848 - i'm suggesting you work on something else for now.

**Comment by nathenf** [comment]
@rufuspollock would you like these definitions added as individual notes as with the previous glossary?

**Comment by alexianetcu** [comment]
@rufuspollock new terms added after small tweaks were made for better grammar and flow. let me know if it (https://lifeitself.org/notes/glossary) looks good to you know, so I can close issue or add anything else.

**Comment by alexianetcu** [comment]
FIXED. Glossary updated.
