### ISSUE TITLE
Identify intentional community / conscious coliving related places to advertise residencies

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#93]
When sharing the residencies I want to know of intentional community related places online where this could be shared because this is relevant to people interested in intentional communities.

## Acceptance
Have list of intentional community groups and forums ready to post whenever we want to advertise a residency.

## Tasks
- [x] Search for appropriate groups online ✅ 2024-01-22 [This spreadsheet](https://docs.google.com/spreadsheets/d/1EKnEgJ5PjfVUiFEOb6nE6vZ9NyPEsA5Ov_vT4gDbK1g/edit#gid=207124184) includes public groups and forums that we could post into. The bottom of the list has more general groups from Nathen and Lauren's Conscious Coliving outreach research, and the top part are groups on specific topics that our residencies are usually about.
- [x] put this information in Barbacane README for future Comms people to be able to access ✅ 2024-01-22

**Comment by rufuspollock** [comment]
@alexianetcu what happened on this one?

**Comment by alexianetcu** [comment]
FIXED. Groups to promote residencies identified.
