### ISSUE TITLE
Transforming Conflict Launch Strategy

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#936]
Create an actionable launch strategy to promote #896 

## Acceptance
- [ ] Launch Strategy Created
- [x] Course launched
- [x] 20 sign ups by 10th Dec
- [x] Launch date agreed and launched - 7th December 🚧 _there is an issue with the Brevo automation. I'm in conversation with Brevo about it_

### Pre-launch
- [x] Promote in #887 
- [x] Announce in whatsapp group
- [x] Announce on LinkedIn
- [x] Announce on Twitter
- [x] Announce on Instagram
- [x] Blog post announcing it's launch written @moonimmisch _I want you to have a go at writing this please more details in the comments_
- [x] Create post-launch strategy for promotion (to include subreddits and blogs)

### Post-launch
- [x] Official LAUNCHED email 
- [x] Headlines and hooks for content _below_ 
- [ ] [Future blog posts written](https://drive.google.com/drive/folders/1dxaFP9-TWwn09LL91WxnXNeMDeooVPAq)
  - [ ] 8 blog posts written from w/c 11th Dec until w/c 29th January from topics below
- [ ] [List of potential people to have on community calls in 2024](https://docs.google.com/spreadsheets/d/1Oz09uehrtQLes6-W2oRklbMSUN4v6JYCqeT1krNWBIE/edit#gid=869164973)
  - [ ] Individuals invited via email
- [ ] Identify key entry points to access audience (AKA which FB Groups, Subreddits?)
- [ ] Reach out to Allies to share for course launch 
  - [ ] draft email in launch doc
- [x] Announce in whatsapp group
- [x] Announce on LinkedIn
- [x] Announce on Twitter
- [x] Announce on Instagram
- [ ] Post in sub-reddits
- [ ] Create Epic for 2024 promo for Transforming Conflict / CC101 (and Practical Action once launched)

### Headlines and hooks list for content and blog posts for next 6 months (Dec 2023-May 2024)
TBA

## Launch Strategy Diagram
![Transforming Conflict Launch Strategy (1)](https://github.com/life-itself/community/assets/132304704/14782289-222d-4f91-839c-962150a9911d)

**Comment by moonimmisch** [comment]
@laurenwigmore The content is written here (https://docs.google.com/document/d/1l3nNT97f7khFO0efFzulowC2kQ6pZLw6AJSdnqZtRSA/edit) for posting, the only thing I have had a slight blocker with is updating the canva image to say communities instead of CC. Also still need to make visual assets for IG still. I was trying to find the ones from the CC101 as a template to what would be good for an IG carousel for the launching of a course but couldn't find it on IG or canva.

**Comment by moonimmisch** [comment]
Hook Line Ideas:

From Discord to Connection: Revolutionising Conflict Resolution in Community Living.

Bridging Differences: Transforming Conflict for a Resilient Community Spirit.

Empower Through Understanding: Building Stronger Bonds in Community Relationships.

Cultivating Harmony: Explore Transformative Conflict Resolution in Community Living.

Building Bridges, Not Walls: A New Approach to Conflict Resolution in Communities.

Awaken to Connection: Exploring Transformative Conflict Resolution in Communities.

The Art of Peaceful Coexistence: A Deep Dive into Transformative Conflict Resolution in Community Living.

**Comment by moonimmisch** [comment]
As well as joining the subreddits listed I thought it might be good to find some others that may have interesting likeminded individuals in. I found and joined the following subreddits as well:

r/Permaculture
r/TheNewCommunity
r/intentionalcommunity
r/solarpunk
r/cooperatives
r/ecotribe
r/Futurology
r/SelfSufficiency
r/homestead

**Comment by moonimmisch** [comment]
Blog ideas for Conflict Transforming: 

 1.  **How Conflict Transformation Impacts Individual Growth**: We could ask life itself members to contribute personal experiences about conflict & their own growth. * Use the Bergerac hub as an example, see how people there have overcome conflict there. 
 2. **Art of Dialogue: Transformative Conversations Beyond Conflict**: * Highlighting the power of open communication and dialogue in community dynamics. Discussing how conflict fosters adaptability and fuels positive community evolution. Challenging stereotypes by showcasing the constructive outcomes of conflicts in communities.
 3. **Community Governance: Structures for Effective Conflict Resolution**: A look into how communities are governed and what  structures are put in place to avoid/deal with conflict. Could look into a couple communities. Bergerac as well as others. This idea would also probably require some primary research to be conducted. 
 4. **Future Horizons: How Conflict Transformation Shapes Tomorrow's Communities**: Speculating on the role of conflict resolution in shaping the future landscape of communal living.Potentially a slightly ambitious topic but definitely interesting.

**Comment by moonimmisch** [comment]
Note: Transforming Conflict Video made & uploaded here for storage: https://drive.google.com/drive/folders/133CgSoydwWZlTagL6_mNfJGNhAsIsd1_

**Comment by laurenwigmore** [comment]
Fixed. Course launched - 57 sign ups throughout December. Further issues will be created for 2024 related promotion.
