### ISSUE TITLE
Making necessary edits on the Life Itself Tao to comply with Obsidian update

### ISSUE THREAD

**Issue by matthewmccarthy11** [life-itself/community#967]
## Job Story 

Some pages on the Life Itself Tao have ' : : : '  on them, and they don't show up correctly. We want to go through all of the pages on https://lifeitself.org/tao and make sure that there are no mistakes of this kind.

<img width="385" alt="screenshottaolifeitself" src="https://github.com/life-itself/community/assets/131390186/dc2bcecb-3bd2-46b1-872c-ad64103aa6d9">

## Acceptance 

- [x] All of the pages have been reviewed and edits have been made.

## Tasks 

- [x] Go through all of the individual pages associated with https://lifeitself.org/tao and make the necessary edits through obsidian of deleting or updating whatever should be in place of the ': : :'

**Comment by rufuspollock** [comment]
@matthewmccarthy11 can you be clearer about the issue exactly ... e.g. this isn't about an "obsidian update". I would just state clearly with e.g. a screenshot of the issue and then explain how you are going to fix it ...

**Comment by rufuspollock** [comment]
@matthewmccarthy11 i believe this relates to https://github.com/life-itself/community/pull/966 which i commented on. Could you resolve the items i mentioned so we could get this closed?

**Comment by matthewmccarthy11** [comment]
FIXED: There are no more spots on the Tao which have the ' : : :' typo.
