### ISSUE TITLE
Add patterns re Processing material from meetings to Tao

### ISSUE THREAD

**Issue by catherinet1** [life-itself/community#986]
## Acceptance

- [x] Location identified to add this material or new page in Tao created **✅2024-01-17 it's lifeitself.org/tao/meetings**
- [x] Material from discussion thread edited and added to Tao: https://github.com/orgs/life-itself/discussions/958 **✅2024-01-17 see https://github.com/life-itself/community/blob/main/content/tao/meetings.md**
- [x] Discussion is closed and/or deleted (deleted is sometimes good as it reduces noise in the forum - IMO i should have probably opened this item as an issue rather than a discussion ...) **✅2024-01-17 deleted forum thread github.com/orgs/life-itself/discussions/958**

cf Analysis section in https://github.com/life-itself/ecosystem/issues/193 for example

**Comment by rufuspollock** [comment]
@catherinet1 let's just add it to `/tao/meetings`. Do you want to take the lead on this - it should be very quick.

**Comment by rufuspollock** [comment]
FIXED.

**Comment by catherinet1** [comment]
Just seeing this, thanks, @rufuspollock 👍 . Thanks also for note re closing/deleting discussion to reduce noise in forum)
