### ISSUE TITLE
Issues with setup/learning github desktop & obsidian

### ISSUE THREAD

**Issue by moonimmisch** [life-itself/community#996]
I have had issues setting up github desktop & obsidian, I have tried several times on two different computers and have reached varied levels of success. 

## Steps Taken

- [x] Setup both programs on my old computer but not sure if it was done correctly 
- [x] Lauren looked over but some issue with syncing possibly occurred
- [x] Got a new computer, tried again using several tutorials added the wrong repository to github desktop (ecosystem) and didn't see the pages or blogs section so unable to upload to website
- [x] Tutorials read: 
- [x] https://docs.google.com/document/d/1Kgf4zQ58c6iJFRU5KXz24KFcjAlgFvmHVn-SJkfpcis/edit#heading=h.wsfx2ixz52w9
- [x] https://drive.google.com/drive/search?q=obsidian
- [x] https://docs.google.com/document/d/11pnRk_dbxT3NmoLvZ_IQDnebRm4UCaX2-e3E29t_Ujc/edit#heading=h.77z1ns7gwg13
- [x] https://drive.google.com/drive/search?q=obsidian
- [ ] https://docs.google.com/document/d/1RcwjaJYn0jtMw9rOR9W0Gv2fmQDd7Fjr53NM6j1-lco/edit#heading=h.vkkc3zo06um7
- [x] https://portaljs.org/blog/edit-a-website-locally
- [x] Added the correct repository (community), however now was unable to change the connection to obsidian even when deleting the program & re-downloading it so unsure how to continue 
- [x] Emailed Ola asking for technical support
- [ ] Issue Solved
- [ ] First blog successfully updated using desktop/obsidian

**Comment by moonimmisch** [comment]
Screenshots of websites uploaded to old laptop:
<img width="1512" alt="Screenshot 2024-01-12 at 14 47 17" src="https://github.com/life-itself/community/assets/148585060/26d824ef-0019-489b-bcac-bc1808969242">
<img width="897" alt="Screenshot 2024-01-12 at 14 47 36" src="https://github.com/life-itself/community/assets/148585060/7f809ec2-5434-4f76-88fa-6d87774a253d">

**Comment by moonimmisch** [comment]
Current screenshots of programs: 
<img width="1144" alt="Screenshot 2024-01-12 at 14 57 19" src="https://github.com/life-itself/community/assets/148585060/aa2963d9-69c6-4467-9e33-43d3e3f14d81">
<img width="1018" alt="Screenshot 2024-01-12 at 14 57 47" src="https://github.com/life-itself/community/assets/148585060/789beb02-63af-4ccf-a63a-f05eec2ad830">

**Comment by laurenwigmore** [comment]
@moonimmisch - if you have added a vault to Obsidian - please remove this
<img width="623" alt="image" src="https://github.com/life-itself/community/assets/132304704/c439f60e-2d50-4a67-a633-3f9040084742">

Then use this guide  https://makeitmarkdown.flowershow.app/learn/introduction
When you add the vault folder - select the CONTENT folder (not the whole thing)
<img width="564" alt="image" src="https://github.com/life-itself/community/assets/132304704/4347014c-26c0-4a77-994e-90bf9f126aa9">

**Comment by moonimmisch** [comment]
With @laurenwigmore's help I have now got github desktop & obsidian up & running!
