### ISSUE TITLE
lifeitself.org/research updated with info for people who join

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#999]
Research page updated for info for people who join ...

See "What is Life Itself Research" [collective short notes from 22 Dec 2023 meeting](https://docs.google.com/document/d/1A3bTDHVrlVH7OxpOJadM8Jk65hTf2JKOHn05yukfx1A/edit#heading=h.oty3ldpkqbc4) (can just copy and paste and then inline material) 

- Form/inspirations https://link.excalidraw.com/l/9u8crB2ZmUo/5IkQ56H4ERp 
  - Inspiration in a different area https://www.inkandswitch.com/ 
- Two main workstreams: https://github.com/orgs/life-itself/discussions/924
- FAQ
  - Can I come up with my own project or interest?
  - How many people come? Normally there are others

## Acceptance

- [ ] Section on lifeitself.org/research (e.g. `About`) that gives key info

Extras

- [ ] Profiles of key members
- [ ] FAQs

### Brainstorm Matthew 

- Outline: what is it that we do?
- Diagrams outlining our research overview 
    - 
- Links to resources to get introduced to what we are doing 
    - Blog posts 
    - Summary of 2023 efforts 
- Opportunities for initial engagement 
    - Github discussion forum 
- FAQ about the reserach community
    - Can I come up with my own project or interest?
    - Who is involved/ how many people come?
    - How can I stay updated?
    - What is the secon renaissance?
- Profiles of members (secondary)

**Comment by rufuspollock** [comment]
@matthewmccarthy11 could you take a lead on getting a pull request in for this ...

**Comment by matthewmccarthy11** [comment]
Working on that now @rufuspollock . Instead of the diagram we currently have, the one with the bubbles, should we replace that with the new diagram of our research questions/efforts? from #924

**Comment by rufuspollock** [comment]
@matthewmccarthy11 on https://lifeitself.org/research!

**Comment by rufuspollock** [comment]
FIXED. Page updated with this information. https://lifeitself.org/research

![image](https://github.com/life-itself/community/assets/180658/c37367f9-84da-4e4b-aef5-ff56b11d57eb)
